/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {19, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {23, 1, 1};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};
static const casadi_real casadi_c1[3] = {0., 0., 1.};
static const casadi_real casadi_c2[3] = {0., 0., 9.8100000000000005e+00};
static const casadi_real casadi_c3[9] = 
  {4.1597337770382700e+02, 0., 0., 0., 4.2016806722689074e+02, 0., 0., 0.,
  3.5714285714285717e+02};
static const casadi_real casadi_c4[9] = 
  {2.4039999999999999e-03, 0., 0., 0., 2.3800000000000002e-03, 0., 0., 0.,
  2.8000000000000000e-03};

static const casadi_real casadi_zeros[19] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* quadrotor_impl_dae_fun:(i0[19],i1[19],i2[4],i3[],i4[],i5[23])->(o0[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+4, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, *w14=w+36, w15, w16, w17, w18, w19, *w20=w+44, *w21=w+47, w22;
  casadi_real *w23=w+57, w24, *w25=w+61, *w26=w+64, *w27=w+67, *w28=w+76, *w29=w+85, *w30=w+94, w31, w32, w33, w34;
  casadi_real w35, w36, w37, w38, *w39=w+106, *w40=w+110, *w41=w+114, *w42=w+118, *w43=w+122, *w44=w+138, *w45=w+154;
  const casadi_real *cr, *cs, *ct, *wr00, *wr21, *wr28;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: @1 = input[0][3] */
  w01 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = input[0][4] */
  w02 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = input[0][5] */
  w03 = arg[0] ? arg[0][5] : 0;
  /* #4: @4 = 0.0136986 */
  w04 = 1.3698630136986302e-02;
  /* #5: @5 = 0.4032 */
  w05 = 4.0320000000000000e-01;
  /* #6: @6 = input[0][1] */
  w06 = arg[0] ? arg[0][1] : 0;
  /* #7: @7 = input[0][7] */
  w07 = arg[0] ? arg[0][7] : 0;
  /* #8: @8 = (@6-@7) */
  w08  = (w06-w07);
  /* #9: @9 = input[0][0] */
  w09 = arg[0] ? arg[0][0] : 0;
  /* #10: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #11: @11 = (@9-@10) */
  w11  = (w09-w10);
  /* #12: @6 = (@6-@7) */
  w06 -= w07;
  /* #13: @7 = input[0][2] */
  w07 = arg[0] ? arg[0][2] : 0;
  /* #14: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #15: @13 = (@7-@12) */
  w13  = (w07-w12);
  /* #16: @14 = vertcat(@11, @6, @13) */
  rr=w14;
  *rr++ = w11;
  *rr++ = w06;
  *rr++ = w13;
  /* #17: @11 = ||@14||_F */
  w11 = casadi_norm_2(3, w14);
  /* #18: @8 = (@8/@11) */
  w08 /= w11;
  /* #19: @6 = input[0][11] */
  w06 = arg[0] ? arg[0][11] : 0;
  /* #20: @13 = (@3-@6) */
  w13  = (w03-w06);
  /* #21: @15 = 0.56 */
  w15 = 5.6000000000000005e-01;
  /* #22: @13 = (@13/@15) */
  w13 /= w15;
  /* #23: @15 = (@8*@13) */
  w15  = (w08*w13);
  /* #24: @7 = (@7-@12) */
  w07 -= w12;
  /* #25: @7 = (@7/@11) */
  w07 /= w11;
  /* #26: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #27: @16 = (@2-@12) */
  w16  = (w02-w12);
  /* #28: @17 = 0.56 */
  w17 = 5.6000000000000005e-01;
  /* #29: @16 = (@16/@17) */
  w16 /= w17;
  /* #30: @17 = (@7*@16) */
  w17  = (w07*w16);
  /* #31: @15 = (@15-@17) */
  w15 -= w17;
  /* #32: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #33: @18 = (@1-@17) */
  w18  = (w01-w17);
  /* #34: @19 = 0.56 */
  w19 = 5.6000000000000005e-01;
  /* #35: @18 = (@18/@19) */
  w18 /= w19;
  /* #36: @19 = (@7*@18) */
  w19  = (w07*w18);
  /* #37: @9 = (@9-@10) */
  w09 -= w10;
  /* #38: @9 = (@9/@11) */
  w09 /= w11;
  /* #39: @13 = (@9*@13) */
  w13  = (w09*w13);
  /* #40: @19 = (@19-@13) */
  w19 -= w13;
  /* #41: @16 = (@9*@16) */
  w16  = (w09*w16);
  /* #42: @18 = (@8*@18) */
  w18  = (w08*w18);
  /* #43: @16 = (@16-@18) */
  w16 -= w18;
  /* #44: @14 = vertcat(@15, @19, @16) */
  rr=w14;
  *rr++ = w15;
  *rr++ = w19;
  *rr++ = w16;
  /* #45: @15 = dot(@14, @14) */
  w15 = casadi_dot(3, w14, w14);
  /* #46: @5 = (@5*@15) */
  w05 *= w15;
  /* #47: @14 = vertcat(@9, @8, @7) */
  rr=w14;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w07;
  /* #48: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #49: @9 = input[2][0] */
  w09 = arg[2] ? arg[2][0] : 0;
  /* #50: @8 = input[2][1] */
  w08 = arg[2] ? arg[2][1] : 0;
  /* #51: @7 = (@9+@8) */
  w07  = (w09+w08);
  /* #52: @15 = input[2][2] */
  w15 = arg[2] ? arg[2][2] : 0;
  /* #53: @7 = (@7+@15) */
  w07 += w15;
  /* #54: @19 = input[2][3] */
  w19 = arg[2] ? arg[2][3] : 0;
  /* #55: @7 = (@7+@19) */
  w07 += w19;
  /* #56: @21 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr21 = casadi_c0;
  /* #57: @16 = input[0][12] */
  w16 = arg[0] ? arg[0][12] : 0;
  /* #58: @18 = (2.*@16) */
  w18 = (2.* w16 );
  /* #59: @13 = 0 */
  w13 = 0.;
  /* #60: @11 = input[0][15] */
  w11 = arg[0] ? arg[0][15] : 0;
  /* #61: @10 = (-@11) */
  w10 = (- w11 );
  /* #62: @22 = input[0][14] */
  w22 = arg[0] ? arg[0][14] : 0;
  /* #63: @23 = horzcat(@13, @10, @22) */
  rr=w23;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w22;
  /* #64: @23 = @23' */
  /* #65: @13 = 0 */
  w13 = 0.;
  /* #66: @10 = input[0][13] */
  w10 = arg[0] ? arg[0][13] : 0;
  /* #67: @24 = (-@10) */
  w24 = (- w10 );
  /* #68: @25 = horzcat(@11, @13, @24) */
  rr=w25;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w24;
  /* #69: @25 = @25' */
  /* #70: @13 = (-@22) */
  w13 = (- w22 );
  /* #71: @24 = 0 */
  w24 = 0.;
  /* #72: @26 = horzcat(@13, @10, @24) */
  rr=w26;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w24;
  /* #73: @26 = @26' */
  /* #74: @27 = horzcat(@23, @25, @26) */
  rr=w27;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #75: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #76: @28 = (@18*@28) */
  for (i=0, rr=w28, cs=w28; i<9; ++i) (*rr++)  = (w18*(*cs++));
  /* #77: @21 = (@21+@28) */
  for (i=0, rr=w21, cr=wr21, cs=w28; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #78: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #79: @18 = 0 */
  w18 = 0.;
  /* #80: @13 = (-@11) */
  w13 = (- w11 );
  /* #81: @23 = horzcat(@18, @13, @22) */
  rr=w23;
  *rr++ = w18;
  *rr++ = w13;
  *rr++ = w22;
  /* #82: @23 = @23' */
  /* #83: @18 = 0 */
  w18 = 0.;
  /* #84: @13 = (-@10) */
  w13 = (- w10 );
  /* #85: @25 = horzcat(@11, @18, @13) */
  rr=w25;
  *rr++ = w11;
  *rr++ = w18;
  *rr++ = w13;
  /* #86: @25 = @25' */
  /* #87: @18 = (-@22) */
  w18 = (- w22 );
  /* #88: @13 = 0 */
  w13 = 0.;
  /* #89: @26 = horzcat(@18, @10, @13) */
  rr=w26;
  *rr++ = w18;
  *rr++ = w10;
  *rr++ = w13;
  /* #90: @26 = @26' */
  /* #91: @27 = horzcat(@23, @25, @26) */
  rr=w27;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #92: @29 = @27' */
  for (i=0, rr=w29, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #93: @28 = mac(@29,@29,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=w29+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #94: @28 = (2.*@28) */
  for (i=0, rr=w28, cs=w28; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #95: @21 = (@21+@28) */
  for (i=0, rr=w21, cs=w28; i<9; ++i) (*rr++) += (*cs++);
  /* #96: @21 = (@7*@21) */
  for (i=0, rr=w21, cs=w21; i<9; ++i) (*rr++)  = (w07*(*cs++));
  /* #97: @23 = [0, 0, 1] */
  casadi_copy(casadi_c1, 3, w23);
  /* #98: @20 = mac(@21,@23,@20) */
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w21+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #99: @7 = dot(@14, @20) */
  w07 = casadi_dot(3, w14, w20);
  /* #100: @5 = (@5-@7) */
  w05 -= w07;
  /* #101: @4 = (@4*@5) */
  w04 *= w05;
  /* #102: @14 = (@4*@14) */
  for (i=0, rr=w14, cs=w14; i<3; ++i) (*rr++)  = (w04*(*cs++));
  /* #103: @4 = 0.01 */
  w04 = 1.0000000000000000e-02;
  /* #104: @23 = (@14/@4) */
  for (i=0, rr=w23, cr=w14; i<3; ++i) (*rr++)  = ((*cr++)/w04);
  /* #105: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) *rr++ = (- *cs++ );
  /* #106: @25 = [0, 0, 9.81] */
  casadi_copy(casadi_c2, 3, w25);
  /* #107: @23 = (@23-@25) */
  for (i=0, rr=w23, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #108: @4 = @23[0] */
  for (rr=(&w04), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #109: @5 = @23[1] */
  for (rr=(&w05), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #110: @7 = @23[2] */
  for (rr=(&w07), cs=w23+2; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #111: @20 = (@20+@14) */
  for (i=0, rr=w20, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #112: @18 = 0.72 */
  w18 = 7.1999999999999997e-01;
  /* #113: @20 = (@20/@18) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w18;
  /* #114: @14 = [0, 0, 9.81] */
  casadi_copy(casadi_c2, 3, w14);
  /* #115: @20 = (@20-@14) */
  for (i=0, rr=w20, cs=w14; i<3; ++i) (*rr++) -= (*cs++);
  /* #116: @18 = @20[0] */
  for (rr=(&w18), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #117: @13 = @20[1] */
  for (rr=(&w13), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #118: @24 = @20[2] */
  for (rr=(&w24), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #119: @30 = zeros(4x1) */
  casadi_clear(w30, 4);
  /* #120: @31 = 0.5 */
  w31 = 5.0000000000000000e-01;
  /* #121: @32 = 0 */
  w32 = 0.;
  /* #122: @33 = input[0][16] */
  w33 = arg[0] ? arg[0][16] : 0;
  /* #123: @34 = (-@33) */
  w34 = (- w33 );
  /* #124: @35 = input[0][17] */
  w35 = arg[0] ? arg[0][17] : 0;
  /* #125: @36 = (-@35) */
  w36 = (- w35 );
  /* #126: @37 = input[0][18] */
  w37 = arg[0] ? arg[0][18] : 0;
  /* #127: @38 = (-@37) */
  w38 = (- w37 );
  /* #128: @39 = horzcat(@32, @34, @36, @38) */
  rr=w39;
  *rr++ = w32;
  *rr++ = w34;
  *rr++ = w36;
  *rr++ = w38;
  /* #129: @39 = @39' */
  /* #130: @32 = 0 */
  w32 = 0.;
  /* #131: @34 = (-@35) */
  w34 = (- w35 );
  /* #132: @40 = horzcat(@33, @32, @37, @34) */
  rr=w40;
  *rr++ = w33;
  *rr++ = w32;
  *rr++ = w37;
  *rr++ = w34;
  /* #133: @40 = @40' */
  /* #134: @32 = (-@37) */
  w32 = (- w37 );
  /* #135: @34 = 0 */
  w34 = 0.;
  /* #136: @41 = horzcat(@35, @32, @34, @33) */
  rr=w41;
  *rr++ = w35;
  *rr++ = w32;
  *rr++ = w34;
  *rr++ = w33;
  /* #137: @41 = @41' */
  /* #138: @32 = (-@33) */
  w32 = (- w33 );
  /* #139: @34 = 0 */
  w34 = 0.;
  /* #140: @42 = horzcat(@37, @35, @32, @34) */
  rr=w42;
  *rr++ = w37;
  *rr++ = w35;
  *rr++ = w32;
  *rr++ = w34;
  /* #141: @42 = @42' */
  /* #142: @43 = horzcat(@39, @40, @41, @42) */
  rr=w43;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<4; ++i) *rr++ = *cs++;
  /* #143: @44 = @43' */
  for (i=0, rr=w44, cs=w43; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #144: @44 = (@31*@44) */
  for (i=0, rr=w44, cs=w44; i<16; ++i) (*rr++)  = (w31*(*cs++));
  /* #145: @39 = vertcat(@16, @10, @22, @11) */
  rr=w39;
  *rr++ = w16;
  *rr++ = w10;
  *rr++ = w22;
  *rr++ = w11;
  /* #146: @30 = mac(@44,@39,@30) */
  for (i=0, rr=w30; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w44+j, ct=w39+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #147: @16 = 1 */
  w16 = 1.;
  /* #148: @10 = ||@39||_F */
  w10 = casadi_norm_2(4, w39);
  /* #149: @16 = (@16-@10) */
  w16 -= w10;
  /* #150: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #151: @39 = (@16*@39) */
  for (i=0, rr=w39, cs=w39; i<4; ++i) (*rr++)  = (w16*(*cs++));
  /* #152: @30 = (@30+@39) */
  for (i=0, rr=w30, cs=w39; i<4; ++i) (*rr++) += (*cs++);
  /* #153: @16 = @30[0] */
  for (rr=(&w16), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #154: @10 = @30[1] */
  for (rr=(&w10), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #155: @22 = @30[2] */
  for (rr=(&w22), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #156: @11 = @30[3] */
  for (rr=(&w11), cs=w30+3; cs!=w30+4; cs+=1) *rr++ = *cs;
  /* #157: @20 = zeros(3x1) */
  casadi_clear(w20, 3);
  /* #158: @21 = 
  [[415.973, 0, 0], 
   [0, 420.168, 0], 
   [0, 0, 357.143]] */
  wr21 = casadi_c3;
  /* #159: @31 = 0.105 */
  w31 = 1.0500000000000000e-01;
  /* #160: @31 = (@31*@9) */
  w31 *= w09;
  /* #161: @32 = 0.105 */
  w32 = 1.0500000000000000e-01;
  /* #162: @32 = (@32*@8) */
  w32 *= w08;
  /* #163: @31 = (@31+@32) */
  w31 += w32;
  /* #164: @32 = 0.105 */
  w32 = 1.0500000000000000e-01;
  /* #165: @32 = (@32*@15) */
  w32 *= w15;
  /* #166: @31 = (@31-@32) */
  w31 -= w32;
  /* #167: @32 = 0.105 */
  w32 = 1.0500000000000000e-01;
  /* #168: @32 = (@32*@19) */
  w32 *= w19;
  /* #169: @31 = (@31-@32) */
  w31 -= w32;
  /* #170: @32 = -0.0784 */
  w32 = -7.8399999999999997e-02;
  /* #171: @32 = (@32*@9) */
  w32 *= w09;
  /* #172: @34 = 0.0816 */
  w34 = 8.1600000000000006e-02;
  /* #173: @34 = (@34*@8) */
  w34 *= w08;
  /* #174: @32 = (@32+@34) */
  w32 += w34;
  /* #175: @34 = 0.0816 */
  w34 = 8.1600000000000006e-02;
  /* #176: @34 = (@34*@15) */
  w34 *= w15;
  /* #177: @32 = (@32+@34) */
  w32 += w34;
  /* #178: @34 = 0.0784 */
  w34 = 7.8399999999999997e-02;
  /* #179: @34 = (@34*@19) */
  w34 *= w19;
  /* #180: @32 = (@32-@34) */
  w32 -= w34;
  /* #181: @34 = 0.0152273 */
  w34 = 1.5227272727272728e-02;
  /* #182: @9 = (@9-@8) */
  w09 -= w08;
  /* #183: @9 = (@9+@15) */
  w09 += w15;
  /* #184: @9 = (@9-@19) */
  w09 -= w19;
  /* #185: @34 = (@34*@9) */
  w34 *= w09;
  /* #186: @14 = vertcat(@31, @32, @34) */
  rr=w14;
  *rr++ = w31;
  *rr++ = w32;
  *rr++ = w34;
  /* #187: @23 = zeros(3x1) */
  casadi_clear(w23, 3);
  /* #188: @28 = 
  [[0.002404, 0, 0], 
   [0, 0.00238, 0], 
   [0, 0, 0.0028]] */
  wr28 = casadi_c4;
  /* #189: @25 = vertcat(@33, @35, @37) */
  rr=w25;
  *rr++ = w33;
  *rr++ = w35;
  *rr++ = w37;
  /* #190: @23 = mac(@28,@25,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr28+j, ct=w25+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #191: @31 = @23[2] */
  for (rr=(&w31), cs=w23+2; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #192: @32 = (@35*@31) */
  w32  = (w35*w31);
  /* #193: @34 = @23[1] */
  for (rr=(&w34), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #194: @9 = (@37*@34) */
  w09  = (w37*w34);
  /* #195: @32 = (@32-@9) */
  w32 -= w09;
  /* #196: @9 = @23[0] */
  for (rr=(&w09), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #197: @37 = (@37*@9) */
  w37 *= w09;
  /* #198: @31 = (@33*@31) */
  w31  = (w33*w31);
  /* #199: @37 = (@37-@31) */
  w37 -= w31;
  /* #200: @33 = (@33*@34) */
  w33 *= w34;
  /* #201: @35 = (@35*@9) */
  w35 *= w09;
  /* #202: @33 = (@33-@35) */
  w33 -= w35;
  /* #203: @23 = vertcat(@32, @37, @33) */
  rr=w23;
  *rr++ = w32;
  *rr++ = w37;
  *rr++ = w33;
  /* #204: @14 = (@14-@23) */
  for (i=0, rr=w14, cs=w23; i<3; ++i) (*rr++) -= (*cs++);
  /* #205: @20 = mac(@21,@14,@20) */
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr21+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #206: @32 = @20[0] */
  for (rr=(&w32), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #207: @37 = @20[1] */
  for (rr=(&w37), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #208: @33 = @20[2] */
  for (rr=(&w33), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #209: @45 = vertcat(@1, @2, @3, @4, @5, @7, @17, @12, @6, @18, @13, @24, @16, @10, @22, @11, @32, @37, @33) */
  rr=w45;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w17;
  *rr++ = w12;
  *rr++ = w06;
  *rr++ = w18;
  *rr++ = w13;
  *rr++ = w24;
  *rr++ = w16;
  *rr++ = w10;
  *rr++ = w22;
  *rr++ = w11;
  *rr++ = w32;
  *rr++ = w37;
  *rr++ = w33;
  /* #210: @0 = (@0-@45) */
  for (i=0, rr=w00, cr=wr00, cs=w45; i<19; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #211: output[0][0] = @0 */
  casadi_copy(w00, 19, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 25;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 173;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 25*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 173*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
