/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {19, 1, 1};
static const casadi_int casadi_s1[3] = {0, 0, 1};
static const casadi_int casadi_s2[3] = {23, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_c0[9] = 
  {5., 0., 0., 0., 5., 0., 0., 0.,
  10.};

static const casadi_real casadi_zeros[23] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* quadrotor_cost_ext_cost_e_fun_jac:(i0[19],i1[],i2[],i3[23])->(o0,o1[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, *w23=w+46;
  casadi_real *w24=w+49, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  casadi_real w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47;
  casadi_real w48, w49, w50, *w51=w+79, w52, w53, *w54=w+84, *w56=w+96, *w57=w+99;
  const casadi_real *cr, *cs, *ct, *wr02, *wr55;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = input[0][0] */
  w01 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[3][0] */
  wr02 = arg[3] ? arg[3] : casadi_zeros;
  /* #3: @3 = @2[0] */
  w03 = wr02[0];
  /* #4: @1 = (@1-@3) */
  w01 -= w03;
  /* #5: @3 = sq(@1) */
  w03 = casadi_sq( w01 );
  /* #6: @0 = (@0*@3) */
  w00 *= w03;
  /* #7: @3 = 10 */
  w03 = 10.;
  /* #8: @4 = input[0][1] */
  w04 = arg[0] ? arg[0][1] : 0;
  /* #9: @5 = @2[1] */
  w05 = wr02[1];
  /* #10: @4 = (@4-@5) */
  w04 -= w05;
  /* #11: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #12: @3 = (@3*@5) */
  w03 *= w05;
  /* #13: @0 = (@0+@3) */
  w00 += w03;
  /* #14: @3 = 10 */
  w03 = 10.;
  /* #15: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #16: @6 = @2[2] */
  w06 = wr02[2];
  /* #17: @5 = (@5-@6) */
  w05 -= w06;
  /* #18: @6 = sq(@5) */
  w06 = casadi_sq( w05 );
  /* #19: @3 = (@3*@6) */
  w03 *= w06;
  /* #20: @0 = (@0+@3) */
  w00 += w03;
  /* #21: @3 = input[0][3] */
  w03 = arg[0] ? arg[0][3] : 0;
  /* #22: @6 = @2[3] */
  w06 = wr02[3];
  /* #23: @3 = (@3-@6) */
  w03 -= w06;
  /* #24: @6 = sq(@3) */
  w06 = casadi_sq( w03 );
  /* #25: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #26: @0 = (@0+@6) */
  w00 += w06;
  /* #27: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #28: @7 = @2[4] */
  w07 = wr02[4];
  /* #29: @6 = (@6-@7) */
  w06 -= w07;
  /* #30: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #31: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #32: @0 = (@0+@7) */
  w00 += w07;
  /* #33: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #34: @8 = @2[5] */
  w08 = wr02[5];
  /* #35: @7 = (@7-@8) */
  w07 -= w08;
  /* #36: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #37: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #38: @0 = (@0+@8) */
  w00 += w08;
  /* #39: @8 = 10 */
  w08 = 10.;
  /* #40: @9 = input[0][6] */
  w09 = arg[0] ? arg[0][6] : 0;
  /* #41: @10 = @2[6] */
  w10 = wr02[6];
  /* #42: @9 = (@9-@10) */
  w09 -= w10;
  /* #43: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #44: @8 = (@8*@10) */
  w08 *= w10;
  /* #45: @10 = 10 */
  w10 = 10.;
  /* #46: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #47: @12 = @2[7] */
  w12 = wr02[7];
  /* #48: @11 = (@11-@12) */
  w11 -= w12;
  /* #49: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #50: @10 = (@10*@12) */
  w10 *= w12;
  /* #51: @8 = (@8+@10) */
  w08 += w10;
  /* #52: @10 = 10 */
  w10 = 10.;
  /* #53: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #54: @13 = @2[8] */
  w13 = wr02[8];
  /* #55: @12 = (@12-@13) */
  w12 -= w13;
  /* #56: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #57: @10 = (@10*@13) */
  w10 *= w13;
  /* #58: @8 = (@8+@10) */
  w08 += w10;
  /* #59: @0 = (@0+@8) */
  w00 += w08;
  /* #60: @8 = input[0][9] */
  w08 = arg[0] ? arg[0][9] : 0;
  /* #61: @10 = @2[9] */
  w10 = wr02[9];
  /* #62: @8 = (@8-@10) */
  w08 -= w10;
  /* #63: @10 = sq(@8) */
  w10 = casadi_sq( w08 );
  /* #64: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #65: @13 = input[0][10] */
  w13 = arg[0] ? arg[0][10] : 0;
  /* #66: @14 = @2[10] */
  w14 = wr02[10];
  /* #67: @13 = (@13-@14) */
  w13 -= w14;
  /* #68: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #69: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #70: @10 = (@10+@14) */
  w10 += w14;
  /* #71: @14 = input[0][11] */
  w14 = arg[0] ? arg[0][11] : 0;
  /* #72: @15 = @2[11] */
  w15 = wr02[11];
  /* #73: @14 = (@14-@15) */
  w14 -= w15;
  /* #74: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #75: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #76: @10 = (@10+@15) */
  w10 += w15;
  /* #77: @0 = (@0+@10) */
  w00 += w10;
  /* #78: @10 = @2[22] */
  w10 = wr02[22];
  /* #79: @15 = 0.2 */
  w15 = 2.0000000000000001e-01;
  /* #80: @16 = input[0][16] */
  w16 = arg[0] ? arg[0][16] : 0;
  /* #81: @17 = @2[16] */
  w17 = wr02[16];
  /* #82: @16 = (@16-@17) */
  w16 -= w17;
  /* #83: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #84: @17 = (@15*@17) */
  w17  = (w15*w17);
  /* #85: @18 = 0.2 */
  w18 = 2.0000000000000001e-01;
  /* #86: @19 = input[0][17] */
  w19 = arg[0] ? arg[0][17] : 0;
  /* #87: @20 = @2[17] */
  w20 = wr02[17];
  /* #88: @19 = (@19-@20) */
  w19 -= w20;
  /* #89: @20 = sq(@19) */
  w20 = casadi_sq( w19 );
  /* #90: @20 = (@18*@20) */
  w20  = (w18*w20);
  /* #91: @17 = (@17+@20) */
  w17 += w20;
  /* #92: @20 = 0.2 */
  w20 = 2.0000000000000001e-01;
  /* #93: @21 = input[0][18] */
  w21 = arg[0] ? arg[0][18] : 0;
  /* #94: @22 = @2[18] */
  w22 = wr02[18];
  /* #95: @21 = (@21-@22) */
  w21 -= w22;
  /* #96: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #97: @22 = (@20*@22) */
  w22  = (w20*w22);
  /* #98: @17 = (@17+@22) */
  w17 += w22;
  /* #99: @17 = (@10*@17) */
  w17  = (w10*w17);
  /* #100: @0 = (@0+@17) */
  w00 += w17;
  /* #101: @17 = 0 */
  w17 = 0.;
  /* #102: @23 = zeros(1x3) */
  casadi_clear(w23, 3);
  /* #103: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #104: @22 = input[0][12] */
  w22 = arg[0] ? arg[0][12] : 0;
  /* #105: @25 = @2[12] */
  w25 = wr02[12];
  /* #106: @26 = (@22*@25) */
  w26  = (w22*w25);
  /* #107: @27 = input[0][13] */
  w27 = arg[0] ? arg[0][13] : 0;
  /* #108: @28 = @2[13] */
  w28 = wr02[13];
  /* #109: @29 = (@27*@28) */
  w29  = (w27*w28);
  /* #110: @26 = (@26+@29) */
  w26 += w29;
  /* #111: @29 = input[0][14] */
  w29 = arg[0] ? arg[0][14] : 0;
  /* #112: @30 = @2[14] */
  w30 = wr02[14];
  /* #113: @31 = (@29*@30) */
  w31  = (w29*w30);
  /* #114: @26 = (@26+@31) */
  w26 += w31;
  /* #115: @31 = input[0][15] */
  w31 = arg[0] ? arg[0][15] : 0;
  /* #116: @32 = @2[15] */
  w32 = wr02[15];
  /* #117: @33 = (@31*@32) */
  w33  = (w31*w32);
  /* #118: @26 = (@26+@33) */
  w26 += w33;
  /* #119: (@24[0] = @26) */
  for (rr=w24+0, cs=(&w26); rr!=w24+1; rr+=1) *rr = *cs++;
  /* #120: @26 = @2[13] */
  w26 = wr02[13];
  /* #121: @33 = (@22*@26) */
  w33  = (w22*w26);
  /* #122: @34 = @2[12] */
  w34 = wr02[12];
  /* #123: @35 = (@27*@34) */
  w35  = (w27*w34);
  /* #124: @33 = (@33-@35) */
  w33 -= w35;
  /* #125: @35 = @2[14] */
  w35 = wr02[14];
  /* #126: @36 = (@31*@35) */
  w36  = (w31*w35);
  /* #127: @33 = (@33+@36) */
  w33 += w36;
  /* #128: @36 = @2[15] */
  w36 = wr02[15];
  /* #129: @37 = (@29*@36) */
  w37  = (w29*w36);
  /* #130: @33 = (@33-@37) */
  w33 -= w37;
  /* #131: (@24[1] = @33) */
  for (rr=w24+1, cs=(&w33); rr!=w24+2; rr+=1) *rr = *cs++;
  /* #132: @33 = @2[12] */
  w33 = wr02[12];
  /* #133: @37 = (@29*@33) */
  w37  = (w29*w33);
  /* #134: @37 = (-@37) */
  w37 = (- w37 );
  /* #135: @38 = @2[13] */
  w38 = wr02[13];
  /* #136: @39 = (@31*@38) */
  w39  = (w31*w38);
  /* #137: @37 = (@37-@39) */
  w37 -= w39;
  /* #138: @39 = @2[14] */
  w39 = wr02[14];
  /* #139: @40 = (@22*@39) */
  w40  = (w22*w39);
  /* #140: @37 = (@37+@40) */
  w37 += w40;
  /* #141: @40 = @2[15] */
  w40 = wr02[15];
  /* #142: @41 = (@27*@40) */
  w41  = (w27*w40);
  /* #143: @37 = (@37+@41) */
  w37 += w41;
  /* #144: (@24[2] = @37) */
  for (rr=w24+2, cs=(&w37); rr!=w24+3; rr+=1) *rr = *cs++;
  /* #145: @37 = @2[13] */
  w37 = wr02[13];
  /* #146: @29 = (@29*@37) */
  w29 *= w37;
  /* #147: @41 = @2[12] */
  w41 = wr02[12];
  /* #148: @31 = (@31*@41) */
  w31 *= w41;
  /* #149: @29 = (@29-@31) */
  w29 -= w31;
  /* #150: @31 = @2[14] */
  w31 = wr02[14];
  /* #151: @27 = (@27*@31) */
  w27 *= w31;
  /* #152: @29 = (@29-@27) */
  w29 -= w27;
  /* #153: @27 = @2[15] */
  w27 = wr02[15];
  /* #154: @22 = (@22*@27) */
  w22 *= w27;
  /* #155: @29 = (@29+@22) */
  w29 += w22;
  /* #156: (@24[3] = @29) */
  for (rr=w24+3, cs=(&w29); rr!=w24+4; rr+=1) *rr = *cs++;
  /* #157: @29 = @24[0] */
  for (rr=(&w29), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #158: @22 = @24[1] */
  for (rr=(&w22), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #159: @42 = (@29*@22) */
  w42  = (w29*w22);
  /* #160: @43 = @24[2] */
  for (rr=(&w43), cs=w24+2; cs!=w24+3; cs+=1) *rr++ = *cs;
  /* #161: @44 = @24[3] */
  for (rr=(&w44), cs=w24+3; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #162: @45 = (@43*@44) */
  w45  = (w43*w44);
  /* #163: @42 = (@42-@45) */
  w42 -= w45;
  /* #164: @45 = @24[0] */
  for (rr=(&w45), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #165: @46 = @24[2] */
  for (rr=(&w46), cs=w24+2; cs!=w24+3; cs+=1) *rr++ = *cs;
  /* #166: @47 = (@45*@46) */
  w47  = (w45*w46);
  /* #167: @48 = @24[1] */
  for (rr=(&w48), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #168: @49 = @24[3] */
  for (rr=(&w49), cs=w24+3; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #169: @50 = (@48*@49) */
  w50  = (w48*w49);
  /* #170: @47 = (@47+@50) */
  w47 += w50;
  /* #171: @50 = @24[3] */
  for (rr=(&w50), cs=w24+3; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #172: @51 = vertcat(@42, @47, @50) */
  rr=w51;
  *rr++ = w42;
  *rr++ = w47;
  *rr++ = w50;
  /* #173: @42 = 0.001 */
  w42 = 1.0000000000000000e-03;
  /* #174: @47 = @24[0] */
  for (rr=(&w47), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #175: @50 = sq(@47) */
  w50 = casadi_sq( w47 );
  /* #176: @52 = @24[3] */
  for (rr=(&w52), cs=w24+3; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #177: @53 = sq(@52) */
  w53 = casadi_sq( w52 );
  /* #178: @50 = (@50+@53) */
  w50 += w53;
  /* #179: @42 = (@42+@50) */
  w42 += w50;
  /* #180: @42 = sqrt(@42) */
  w42 = sqrt( w42 );
  /* #181: @51 = (@51/@42) */
  for (i=0, rr=w51; i<3; ++i) (*rr++) /= w42;
  /* #182: @54 = @51' */
  casadi_copy(w51, 3, w54);
  /* #183: @55 = 
  [[5, 0, 0], 
   [0, 5, 0], 
   [0, 0, 10]] */
  wr55 = casadi_c0;
  /* #184: @23 = mac(@54,@55,@23) */
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w54+j, ct=wr55+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #185: @17 = mac(@23,@51,@17) */
  for (i=0, rr=(&w17); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w23+j, ct=w51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #186: @0 = (@0+@17) */
  w00 += w17;
  /* #187: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #188: @0 = 10 */
  w00 = 10.;
  /* #189: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #190: @0 = (@0*@1) */
  w00 *= w01;
  /* #191: output[1][0] = @0 */
  if (res[1]) res[1][0] = w00;
  /* #192: @0 = 10 */
  w00 = 10.;
  /* #193: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #194: @0 = (@0*@4) */
  w00 *= w04;
  /* #195: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #196: @0 = 10 */
  w00 = 10.;
  /* #197: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #198: @0 = (@0*@5) */
  w00 *= w05;
  /* #199: output[1][2] = @0 */
  if (res[1]) res[1][2] = w00;
  /* #200: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #201: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #202: output[1][3] = @3 */
  if (res[1]) res[1][3] = w03;
  /* #203: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #204: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #205: output[1][4] = @6 */
  if (res[1]) res[1][4] = w06;
  /* #206: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #207: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #208: output[1][5] = @7 */
  if (res[1]) res[1][5] = w07;
  /* #209: @7 = 10 */
  w07 = 10.;
  /* #210: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #211: @7 = (@7*@9) */
  w07 *= w09;
  /* #212: output[1][6] = @7 */
  if (res[1]) res[1][6] = w07;
  /* #213: @7 = 10 */
  w07 = 10.;
  /* #214: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #215: @7 = (@7*@11) */
  w07 *= w11;
  /* #216: output[1][7] = @7 */
  if (res[1]) res[1][7] = w07;
  /* #217: @7 = 10 */
  w07 = 10.;
  /* #218: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #219: @7 = (@7*@12) */
  w07 *= w12;
  /* #220: output[1][8] = @7 */
  if (res[1]) res[1][8] = w07;
  /* #221: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #222: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #223: output[1][9] = @8 */
  if (res[1]) res[1][9] = w08;
  /* #224: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #225: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #226: output[1][10] = @13 */
  if (res[1]) res[1][10] = w13;
  /* #227: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #228: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #229: output[1][11] = @14 */
  if (res[1]) res[1][11] = w14;
  /* #230: @24 = zeros(4x1) */
  casadi_clear(w24, 4);
  /* #231: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #232: @54 = (@51/@42) */
  for (i=0, rr=w54, cr=w51; i<3; ++i) (*rr++)  = ((*cr++)/w42);
  /* #233: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) *rr++ = (- *cs++ );
  /* #234: @23 = @23' */
  /* #235: @56 = zeros(1x3) */
  casadi_clear(w56, 3);
  /* #236: @51 = @51' */
  /* #237: @57 = @55' */
  for (i=0, rr=w57, cs=wr55; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #238: @56 = mac(@51,@57,@56) */
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w51+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #239: @56 = @56' */
  /* #240: @23 = (@23+@56) */
  for (i=0, rr=w23, cs=w56; i<3; ++i) (*rr++) += (*cs++);
  /* #241: @14 = dot(@54, @23) */
  w14 = casadi_dot(3, w54, w23);
  /* #242: @13 = (2.*@42) */
  w13 = (2.* w42 );
  /* #243: @14 = (@14/@13) */
  w14 /= w13;
  /* #244: @52 = (@52*@14) */
  w52 *= w14;
  /* #245: (@24[3] += @52) */
  for (rr=w24+3, cs=(&w52); rr!=w24+4; rr+=1) *rr += *cs++;
  /* #246: @47 = (2.*@47) */
  w47 = (2.* w47 );
  /* #247: @47 = (@47*@14) */
  w47 *= w14;
  /* #248: (@24[0] += @47) */
  for (rr=w24+0, cs=(&w47); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #249: @23 = (@23/@42) */
  for (i=0, rr=w23; i<3; ++i) (*rr++) /= w42;
  /* #250: {@42, @47, @14} = vertsplit(@23) */
  w42 = w23[0];
  w47 = w23[1];
  w14 = w23[2];
  /* #251: (@24[3] += @14) */
  for (rr=w24+3, cs=(&w14); rr!=w24+4; rr+=1) *rr += *cs++;
  /* #252: @48 = (@48*@47) */
  w48 *= w47;
  /* #253: (@24[3] += @48) */
  for (rr=w24+3, cs=(&w48); rr!=w24+4; rr+=1) *rr += *cs++;
  /* #254: @49 = (@49*@47) */
  w49 *= w47;
  /* #255: (@24[1] += @49) */
  for (rr=w24+1, cs=(&w49); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #256: @45 = (@45*@47) */
  w45 *= w47;
  /* #257: (@24[2] += @45) */
  for (rr=w24+2, cs=(&w45); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #258: @46 = (@46*@47) */
  w46 *= w47;
  /* #259: (@24[0] += @46) */
  for (rr=w24+0, cs=(&w46); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #260: @43 = (@43*@42) */
  w43 *= w42;
  /* #261: @43 = (-@43) */
  w43 = (- w43 );
  /* #262: (@24[3] += @43) */
  for (rr=w24+3, cs=(&w43); rr!=w24+4; rr+=1) *rr += *cs++;
  /* #263: @44 = (@44*@42) */
  w44 *= w42;
  /* #264: @44 = (-@44) */
  w44 = (- w44 );
  /* #265: (@24[2] += @44) */
  for (rr=w24+2, cs=(&w44); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #266: @29 = (@29*@42) */
  w29 *= w42;
  /* #267: (@24[1] += @29) */
  for (rr=w24+1, cs=(&w29); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #268: @22 = (@22*@42) */
  w22 *= w42;
  /* #269: (@24[0] += @22) */
  for (rr=w24+0, cs=(&w22); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #270: @22 = @24[3] */
  for (rr=(&w22), cs=w24+3; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #271: @27 = (@27*@22) */
  w27 *= w22;
  /* #272: @42 = 0 */
  w42 = 0.;
  /* #273: (@24[3] = @42) */
  for (rr=w24+3, cs=(&w42); rr!=w24+4; rr+=1) *rr = *cs++;
  /* #274: @42 = @24[2] */
  for (rr=(&w42), cs=w24+2; cs!=w24+3; cs+=1) *rr++ = *cs;
  /* #275: @39 = (@39*@42) */
  w39 *= w42;
  /* #276: @27 = (@27+@39) */
  w27 += w39;
  /* #277: @39 = 0 */
  w39 = 0.;
  /* #278: (@24[2] = @39) */
  for (rr=w24+2, cs=(&w39); rr!=w24+3; rr+=1) *rr = *cs++;
  /* #279: @39 = @24[1] */
  for (rr=(&w39), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #280: @26 = (@26*@39) */
  w26 *= w39;
  /* #281: @27 = (@27+@26) */
  w27 += w26;
  /* #282: @26 = 0 */
  w26 = 0.;
  /* #283: (@24[1] = @26) */
  for (rr=w24+1, cs=(&w26); rr!=w24+2; rr+=1) *rr = *cs++;
  /* #284: @26 = @24[0] */
  for (rr=(&w26), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #285: @25 = (@25*@26) */
  w25 *= w26;
  /* #286: @27 = (@27+@25) */
  w27 += w25;
  /* #287: output[1][12] = @27 */
  if (res[1]) res[1][12] = w27;
  /* #288: @40 = (@40*@42) */
  w40 *= w42;
  /* #289: @31 = (@31*@22) */
  w31 *= w22;
  /* #290: @40 = (@40-@31) */
  w40 -= w31;
  /* #291: @34 = (@34*@39) */
  w34 *= w39;
  /* #292: @40 = (@40-@34) */
  w40 -= w34;
  /* #293: @28 = (@28*@26) */
  w28 *= w26;
  /* #294: @40 = (@40+@28) */
  w40 += w28;
  /* #295: output[1][13] = @40 */
  if (res[1]) res[1][13] = w40;
  /* #296: @37 = (@37*@22) */
  w37 *= w22;
  /* #297: @33 = (@33*@42) */
  w33 *= w42;
  /* #298: @37 = (@37-@33) */
  w37 -= w33;
  /* #299: @36 = (@36*@39) */
  w36 *= w39;
  /* #300: @37 = (@37-@36) */
  w37 -= w36;
  /* #301: @30 = (@30*@26) */
  w30 *= w26;
  /* #302: @37 = (@37+@30) */
  w37 += w30;
  /* #303: output[1][14] = @37 */
  if (res[1]) res[1][14] = w37;
  /* #304: @38 = (@38*@42) */
  w38 *= w42;
  /* #305: @38 = (-@38) */
  w38 = (- w38 );
  /* #306: @41 = (@41*@22) */
  w41 *= w22;
  /* #307: @38 = (@38-@41) */
  w38 -= w41;
  /* #308: @35 = (@35*@39) */
  w35 *= w39;
  /* #309: @38 = (@38+@35) */
  w38 += w35;
  /* #310: @32 = (@32*@26) */
  w32 *= w26;
  /* #311: @38 = (@38+@32) */
  w38 += w32;
  /* #312: output[1][15] = @38 */
  if (res[1]) res[1][15] = w38;
  /* #313: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #314: @15 = (@15*@10) */
  w15 *= w10;
  /* #315: @16 = (@16*@15) */
  w16 *= w15;
  /* #316: output[1][16] = @16 */
  if (res[1]) res[1][16] = w16;
  /* #317: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #318: @18 = (@18*@10) */
  w18 *= w10;
  /* #319: @19 = (@19*@18) */
  w19 *= w18;
  /* #320: output[1][17] = @19 */
  if (res[1]) res[1][17] = w19;
  /* #321: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #322: @20 = (@20*@10) */
  w20 *= w10;
  /* #323: @21 = (@21*@20) */
  w21 *= w20;
  /* #324: output[1][18] = @21 */
  if (res[1]) res[1][18] = w21;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 108;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 108*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
