/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {19, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {23, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_c0[9] = 
  {5., 0., 0., 0., 5., 0., 0., 0.,
  10.};

static const casadi_real casadi_zeros[23] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* quadrotor_cost_ext_cost_fun:(i0[19],i1[4],i2[],i3[23])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w03, w04, w05, *w06=w+29, *w07=w+32, w08, w09, w10, *w11=w+39;
  casadi_real *w12=w+42;
  const casadi_real *cs, *ct, *wr02, *wr13;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = input[0][0] */
  w01 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[3][0] */
  wr02 = arg[3] ? arg[3] : casadi_zeros;
  /* #3: @3 = @2[0] */
  w03 = wr02[0];
  /* #4: @1 = (@1-@3) */
  w01 -= w03;
  /* #5: @1 = sq(@1) */
  w01 = casadi_sq( w01 );
  /* #6: @0 = (@0*@1) */
  w00 *= w01;
  /* #7: @1 = 10 */
  w01 = 10.;
  /* #8: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #9: @4 = @2[1] */
  w04 = wr02[1];
  /* #10: @3 = (@3-@4) */
  w03 -= w04;
  /* #11: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #12: @1 = (@1*@3) */
  w01 *= w03;
  /* #13: @0 = (@0+@1) */
  w00 += w01;
  /* #14: @1 = 10 */
  w01 = 10.;
  /* #15: @3 = input[0][2] */
  w03 = arg[0] ? arg[0][2] : 0;
  /* #16: @4 = @2[2] */
  w04 = wr02[2];
  /* #17: @3 = (@3-@4) */
  w03 -= w04;
  /* #18: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #19: @1 = (@1*@3) */
  w01 *= w03;
  /* #20: @0 = (@0+@1) */
  w00 += w01;
  /* #21: @1 = input[0][3] */
  w01 = arg[0] ? arg[0][3] : 0;
  /* #22: @3 = @2[3] */
  w03 = wr02[3];
  /* #23: @1 = (@1-@3) */
  w01 -= w03;
  /* #24: @1 = sq(@1) */
  w01 = casadi_sq( w01 );
  /* #25: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #26: @0 = (@0+@1) */
  w00 += w01;
  /* #27: @1 = input[0][4] */
  w01 = arg[0] ? arg[0][4] : 0;
  /* #28: @3 = @2[4] */
  w03 = wr02[4];
  /* #29: @1 = (@1-@3) */
  w01 -= w03;
  /* #30: @1 = sq(@1) */
  w01 = casadi_sq( w01 );
  /* #31: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #32: @0 = (@0+@1) */
  w00 += w01;
  /* #33: @1 = input[0][5] */
  w01 = arg[0] ? arg[0][5] : 0;
  /* #34: @3 = @2[5] */
  w03 = wr02[5];
  /* #35: @1 = (@1-@3) */
  w01 -= w03;
  /* #36: @1 = sq(@1) */
  w01 = casadi_sq( w01 );
  /* #37: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #38: @0 = (@0+@1) */
  w00 += w01;
  /* #39: @1 = 10 */
  w01 = 10.;
  /* #40: @3 = input[0][6] */
  w03 = arg[0] ? arg[0][6] : 0;
  /* #41: @4 = @2[6] */
  w04 = wr02[6];
  /* #42: @3 = (@3-@4) */
  w03 -= w04;
  /* #43: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #44: @1 = (@1*@3) */
  w01 *= w03;
  /* #45: @3 = 10 */
  w03 = 10.;
  /* #46: @4 = input[0][7] */
  w04 = arg[0] ? arg[0][7] : 0;
  /* #47: @5 = @2[7] */
  w05 = wr02[7];
  /* #48: @4 = (@4-@5) */
  w04 -= w05;
  /* #49: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #50: @3 = (@3*@4) */
  w03 *= w04;
  /* #51: @1 = (@1+@3) */
  w01 += w03;
  /* #52: @3 = 10 */
  w03 = 10.;
  /* #53: @4 = input[0][8] */
  w04 = arg[0] ? arg[0][8] : 0;
  /* #54: @5 = @2[8] */
  w05 = wr02[8];
  /* #55: @4 = (@4-@5) */
  w04 -= w05;
  /* #56: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #57: @3 = (@3*@4) */
  w03 *= w04;
  /* #58: @1 = (@1+@3) */
  w01 += w03;
  /* #59: @0 = (@0+@1) */
  w00 += w01;
  /* #60: @1 = input[0][9] */
  w01 = arg[0] ? arg[0][9] : 0;
  /* #61: @3 = @2[9] */
  w03 = wr02[9];
  /* #62: @1 = (@1-@3) */
  w01 -= w03;
  /* #63: @1 = sq(@1) */
  w01 = casadi_sq( w01 );
  /* #64: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #65: @3 = input[0][10] */
  w03 = arg[0] ? arg[0][10] : 0;
  /* #66: @4 = @2[10] */
  w04 = wr02[10];
  /* #67: @3 = (@3-@4) */
  w03 -= w04;
  /* #68: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #69: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #70: @1 = (@1+@3) */
  w01 += w03;
  /* #71: @3 = input[0][11] */
  w03 = arg[0] ? arg[0][11] : 0;
  /* #72: @4 = @2[11] */
  w04 = wr02[11];
  /* #73: @3 = (@3-@4) */
  w03 -= w04;
  /* #74: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #75: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #76: @1 = (@1+@3) */
  w01 += w03;
  /* #77: @0 = (@0+@1) */
  w00 += w01;
  /* #78: @1 = 0.2 */
  w01 = 2.0000000000000001e-01;
  /* #79: @3 = input[0][16] */
  w03 = arg[0] ? arg[0][16] : 0;
  /* #80: @4 = @2[16] */
  w04 = wr02[16];
  /* #81: @3 = (@3-@4) */
  w03 -= w04;
  /* #82: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #83: @1 = (@1*@3) */
  w01 *= w03;
  /* #84: @3 = 0.2 */
  w03 = 2.0000000000000001e-01;
  /* #85: @4 = input[0][17] */
  w04 = arg[0] ? arg[0][17] : 0;
  /* #86: @5 = @2[17] */
  w05 = wr02[17];
  /* #87: @4 = (@4-@5) */
  w04 -= w05;
  /* #88: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #89: @3 = (@3*@4) */
  w03 *= w04;
  /* #90: @1 = (@1+@3) */
  w01 += w03;
  /* #91: @3 = 0.2 */
  w03 = 2.0000000000000001e-01;
  /* #92: @4 = input[0][18] */
  w04 = arg[0] ? arg[0][18] : 0;
  /* #93: @5 = @2[18] */
  w05 = wr02[18];
  /* #94: @4 = (@4-@5) */
  w04 -= w05;
  /* #95: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #96: @3 = (@3*@4) */
  w03 *= w04;
  /* #97: @1 = (@1+@3) */
  w01 += w03;
  /* #98: @0 = (@0+@1) */
  w00 += w01;
  /* #99: @1 = 0 */
  w01 = 0.;
  /* #100: @6 = zeros(1x3) */
  casadi_clear(w06, 3);
  /* #101: @7 = zeros(4x1) */
  casadi_clear(w07, 4);
  /* #102: @3 = input[0][12] */
  w03 = arg[0] ? arg[0][12] : 0;
  /* #103: @4 = @2[12] */
  w04 = wr02[12];
  /* #104: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #105: @5 = input[0][13] */
  w05 = arg[0] ? arg[0][13] : 0;
  /* #106: @8 = @2[13] */
  w08 = wr02[13];
  /* #107: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #108: @4 = (@4+@8) */
  w04 += w08;
  /* #109: @8 = input[0][14] */
  w08 = arg[0] ? arg[0][14] : 0;
  /* #110: @9 = @2[14] */
  w09 = wr02[14];
  /* #111: @9 = (@8*@9) */
  w09  = (w08*w09);
  /* #112: @4 = (@4+@9) */
  w04 += w09;
  /* #113: @9 = input[0][15] */
  w09 = arg[0] ? arg[0][15] : 0;
  /* #114: @10 = @2[15] */
  w10 = wr02[15];
  /* #115: @10 = (@9*@10) */
  w10  = (w09*w10);
  /* #116: @4 = (@4+@10) */
  w04 += w10;
  /* #117: (@7[0] = @4) */
  for (rr=w07+0, cs=(&w04); rr!=w07+1; rr+=1) *rr = *cs++;
  /* #118: @4 = @2[13] */
  w04 = wr02[13];
  /* #119: @4 = (@3*@4) */
  w04  = (w03*w04);
  /* #120: @10 = @2[12] */
  w10 = wr02[12];
  /* #121: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #122: @4 = (@4-@10) */
  w04 -= w10;
  /* #123: @10 = @2[14] */
  w10 = wr02[14];
  /* #124: @10 = (@9*@10) */
  w10  = (w09*w10);
  /* #125: @4 = (@4+@10) */
  w04 += w10;
  /* #126: @10 = @2[15] */
  w10 = wr02[15];
  /* #127: @10 = (@8*@10) */
  w10  = (w08*w10);
  /* #128: @4 = (@4-@10) */
  w04 -= w10;
  /* #129: (@7[1] = @4) */
  for (rr=w07+1, cs=(&w04); rr!=w07+2; rr+=1) *rr = *cs++;
  /* #130: @4 = @2[12] */
  w04 = wr02[12];
  /* #131: @4 = (@8*@4) */
  w04  = (w08*w04);
  /* #132: @4 = (-@4) */
  w04 = (- w04 );
  /* #133: @10 = @2[13] */
  w10 = wr02[13];
  /* #134: @10 = (@9*@10) */
  w10  = (w09*w10);
  /* #135: @4 = (@4-@10) */
  w04 -= w10;
  /* #136: @10 = @2[14] */
  w10 = wr02[14];
  /* #137: @10 = (@3*@10) */
  w10  = (w03*w10);
  /* #138: @4 = (@4+@10) */
  w04 += w10;
  /* #139: @10 = @2[15] */
  w10 = wr02[15];
  /* #140: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #141: @4 = (@4+@10) */
  w04 += w10;
  /* #142: (@7[2] = @4) */
  for (rr=w07+2, cs=(&w04); rr!=w07+3; rr+=1) *rr = *cs++;
  /* #143: @4 = @2[13] */
  w04 = wr02[13];
  /* #144: @8 = (@8*@4) */
  w08 *= w04;
  /* #145: @4 = @2[12] */
  w04 = wr02[12];
  /* #146: @9 = (@9*@4) */
  w09 *= w04;
  /* #147: @8 = (@8-@9) */
  w08 -= w09;
  /* #148: @9 = @2[14] */
  w09 = wr02[14];
  /* #149: @5 = (@5*@9) */
  w05 *= w09;
  /* #150: @8 = (@8-@5) */
  w08 -= w05;
  /* #151: @5 = @2[15] */
  w05 = wr02[15];
  /* #152: @3 = (@3*@5) */
  w03 *= w05;
  /* #153: @8 = (@8+@3) */
  w08 += w03;
  /* #154: (@7[3] = @8) */
  for (rr=w07+3, cs=(&w08); rr!=w07+4; rr+=1) *rr = *cs++;
  /* #155: @8 = @7[0] */
  for (rr=(&w08), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #156: @3 = @7[1] */
  for (rr=(&w03), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #157: @8 = (@8*@3) */
  w08 *= w03;
  /* #158: @3 = @7[2] */
  for (rr=(&w03), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #159: @5 = @7[3] */
  for (rr=(&w05), cs=w07+3; cs!=w07+4; cs+=1) *rr++ = *cs;
  /* #160: @3 = (@3*@5) */
  w03 *= w05;
  /* #161: @8 = (@8-@3) */
  w08 -= w03;
  /* #162: @3 = @7[0] */
  for (rr=(&w03), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #163: @5 = @7[2] */
  for (rr=(&w05), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #164: @3 = (@3*@5) */
  w03 *= w05;
  /* #165: @5 = @7[1] */
  for (rr=(&w05), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #166: @9 = @7[3] */
  for (rr=(&w09), cs=w07+3; cs!=w07+4; cs+=1) *rr++ = *cs;
  /* #167: @5 = (@5*@9) */
  w05 *= w09;
  /* #168: @3 = (@3+@5) */
  w03 += w05;
  /* #169: @5 = @7[3] */
  for (rr=(&w05), cs=w07+3; cs!=w07+4; cs+=1) *rr++ = *cs;
  /* #170: @11 = vertcat(@8, @3, @5) */
  rr=w11;
  *rr++ = w08;
  *rr++ = w03;
  *rr++ = w05;
  /* #171: @8 = 0.001 */
  w08 = 1.0000000000000000e-03;
  /* #172: @3 = @7[0] */
  for (rr=(&w03), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #173: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #174: @5 = @7[3] */
  for (rr=(&w05), cs=w07+3; cs!=w07+4; cs+=1) *rr++ = *cs;
  /* #175: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #176: @3 = (@3+@5) */
  w03 += w05;
  /* #177: @8 = (@8+@3) */
  w08 += w03;
  /* #178: @8 = sqrt(@8) */
  w08 = sqrt( w08 );
  /* #179: @11 = (@11/@8) */
  for (i=0, rr=w11; i<3; ++i) (*rr++) /= w08;
  /* #180: @12 = @11' */
  casadi_copy(w11, 3, w12);
  /* #181: @13 = 
  [[5, 0, 0], 
   [0, 5, 0], 
   [0, 0, 10]] */
  wr13 = casadi_c0;
  /* #182: @6 = mac(@12,@13,@6) */
  for (i=0, rr=w06; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w12+j, ct=wr13+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #183: @1 = mac(@6,@11,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w06+j, ct=w11+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #184: @0 = (@0+@1) */
  w00 += w01;
  /* #185: @1 = 1.5 */
  w01 = 1.5000000000000000e+00;
  /* #186: @8 = input[1][0] */
  w08 = arg[1] ? arg[1][0] : 0;
  /* #187: @3 = @2[19] */
  w03 = wr02[19];
  /* #188: @8 = (@8-@3) */
  w08 -= w03;
  /* #189: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #190: @1 = (@1*@8) */
  w01 *= w08;
  /* #191: @8 = 1.5 */
  w08 = 1.5000000000000000e+00;
  /* #192: @3 = input[1][1] */
  w03 = arg[1] ? arg[1][1] : 0;
  /* #193: @5 = @2[20] */
  w05 = wr02[20];
  /* #194: @3 = (@3-@5) */
  w03 -= w05;
  /* #195: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #196: @8 = (@8*@3) */
  w08 *= w03;
  /* #197: @1 = (@1+@8) */
  w01 += w08;
  /* #198: @8 = 1.5 */
  w08 = 1.5000000000000000e+00;
  /* #199: @3 = input[1][2] */
  w03 = arg[1] ? arg[1][2] : 0;
  /* #200: @5 = @2[21] */
  w05 = wr02[21];
  /* #201: @3 = (@3-@5) */
  w03 -= w05;
  /* #202: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #203: @8 = (@8*@3) */
  w08 *= w03;
  /* #204: @1 = (@1+@8) */
  w01 += w08;
  /* #205: @8 = 1.5 */
  w08 = 1.5000000000000000e+00;
  /* #206: @3 = input[1][3] */
  w03 = arg[1] ? arg[1][3] : 0;
  /* #207: @5 = @2[22] */
  w05 = wr02[22];
  /* #208: @3 = (@3-@5) */
  w03 -= w05;
  /* #209: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #210: @8 = (@8*@3) */
  w08 *= w03;
  /* #211: @1 = (@1+@8) */
  w01 += w08;
  /* #212: @0 = (@0+@1) */
  w00 += w01;
  /* #213: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 54;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 54*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
