/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {19, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {23, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_c0[9] = 
  {5., 0., 0., 0., 5., 0., 0., 0.,
  10.};

static const casadi_real casadi_zeros[23] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* quadrotor_cost_ext_cost_fun_jac:(i0[19],i1[4],i2[],i3[23])->(o0,o1[23]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+43, *w21=w+46, w22, w23;
  casadi_real w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  casadi_real w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, *w47=w+75;
  casadi_real w48, w49, *w50=w+80, w52, w53, w54, w55, *w56=w+96, *w57=w+99;
  const casadi_real *cr, *cs, *ct, *wr02, *wr51;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = input[0][0] */
  w01 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[3][0] */
  wr02 = arg[3] ? arg[3] : casadi_zeros;
  /* #3: @3 = @2[0] */
  w03 = wr02[0];
  /* #4: @1 = (@1-@3) */
  w01 -= w03;
  /* #5: @3 = sq(@1) */
  w03 = casadi_sq( w01 );
  /* #6: @0 = (@0*@3) */
  w00 *= w03;
  /* #7: @3 = 10 */
  w03 = 10.;
  /* #8: @4 = input[0][1] */
  w04 = arg[0] ? arg[0][1] : 0;
  /* #9: @5 = @2[1] */
  w05 = wr02[1];
  /* #10: @4 = (@4-@5) */
  w04 -= w05;
  /* #11: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #12: @3 = (@3*@5) */
  w03 *= w05;
  /* #13: @0 = (@0+@3) */
  w00 += w03;
  /* #14: @3 = 10 */
  w03 = 10.;
  /* #15: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #16: @6 = @2[2] */
  w06 = wr02[2];
  /* #17: @5 = (@5-@6) */
  w05 -= w06;
  /* #18: @6 = sq(@5) */
  w06 = casadi_sq( w05 );
  /* #19: @3 = (@3*@6) */
  w03 *= w06;
  /* #20: @0 = (@0+@3) */
  w00 += w03;
  /* #21: @3 = input[0][3] */
  w03 = arg[0] ? arg[0][3] : 0;
  /* #22: @6 = @2[3] */
  w06 = wr02[3];
  /* #23: @3 = (@3-@6) */
  w03 -= w06;
  /* #24: @6 = sq(@3) */
  w06 = casadi_sq( w03 );
  /* #25: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #26: @0 = (@0+@6) */
  w00 += w06;
  /* #27: @6 = input[0][4] */
  w06 = arg[0] ? arg[0][4] : 0;
  /* #28: @7 = @2[4] */
  w07 = wr02[4];
  /* #29: @6 = (@6-@7) */
  w06 -= w07;
  /* #30: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #31: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #32: @0 = (@0+@7) */
  w00 += w07;
  /* #33: @7 = input[0][5] */
  w07 = arg[0] ? arg[0][5] : 0;
  /* #34: @8 = @2[5] */
  w08 = wr02[5];
  /* #35: @7 = (@7-@8) */
  w07 -= w08;
  /* #36: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #37: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #38: @0 = (@0+@8) */
  w00 += w08;
  /* #39: @8 = 10 */
  w08 = 10.;
  /* #40: @9 = input[0][6] */
  w09 = arg[0] ? arg[0][6] : 0;
  /* #41: @10 = @2[6] */
  w10 = wr02[6];
  /* #42: @9 = (@9-@10) */
  w09 -= w10;
  /* #43: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #44: @8 = (@8*@10) */
  w08 *= w10;
  /* #45: @10 = 10 */
  w10 = 10.;
  /* #46: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #47: @12 = @2[7] */
  w12 = wr02[7];
  /* #48: @11 = (@11-@12) */
  w11 -= w12;
  /* #49: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #50: @10 = (@10*@12) */
  w10 *= w12;
  /* #51: @8 = (@8+@10) */
  w08 += w10;
  /* #52: @10 = 10 */
  w10 = 10.;
  /* #53: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #54: @13 = @2[8] */
  w13 = wr02[8];
  /* #55: @12 = (@12-@13) */
  w12 -= w13;
  /* #56: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #57: @10 = (@10*@13) */
  w10 *= w13;
  /* #58: @8 = (@8+@10) */
  w08 += w10;
  /* #59: @0 = (@0+@8) */
  w00 += w08;
  /* #60: @8 = input[0][9] */
  w08 = arg[0] ? arg[0][9] : 0;
  /* #61: @10 = @2[9] */
  w10 = wr02[9];
  /* #62: @8 = (@8-@10) */
  w08 -= w10;
  /* #63: @10 = sq(@8) */
  w10 = casadi_sq( w08 );
  /* #64: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #65: @13 = input[0][10] */
  w13 = arg[0] ? arg[0][10] : 0;
  /* #66: @14 = @2[10] */
  w14 = wr02[10];
  /* #67: @13 = (@13-@14) */
  w13 -= w14;
  /* #68: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #69: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #70: @10 = (@10+@14) */
  w10 += w14;
  /* #71: @14 = input[0][11] */
  w14 = arg[0] ? arg[0][11] : 0;
  /* #72: @15 = @2[11] */
  w15 = wr02[11];
  /* #73: @14 = (@14-@15) */
  w14 -= w15;
  /* #74: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #75: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #76: @10 = (@10+@15) */
  w10 += w15;
  /* #77: @0 = (@0+@10) */
  w00 += w10;
  /* #78: @10 = 0.2 */
  w10 = 2.0000000000000001e-01;
  /* #79: @15 = input[0][16] */
  w15 = arg[0] ? arg[0][16] : 0;
  /* #80: @16 = @2[16] */
  w16 = wr02[16];
  /* #81: @15 = (@15-@16) */
  w15 -= w16;
  /* #82: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #83: @10 = (@10*@16) */
  w10 *= w16;
  /* #84: @16 = 0.2 */
  w16 = 2.0000000000000001e-01;
  /* #85: @17 = input[0][17] */
  w17 = arg[0] ? arg[0][17] : 0;
  /* #86: @18 = @2[17] */
  w18 = wr02[17];
  /* #87: @17 = (@17-@18) */
  w17 -= w18;
  /* #88: @18 = sq(@17) */
  w18 = casadi_sq( w17 );
  /* #89: @16 = (@16*@18) */
  w16 *= w18;
  /* #90: @10 = (@10+@16) */
  w10 += w16;
  /* #91: @16 = 0.2 */
  w16 = 2.0000000000000001e-01;
  /* #92: @18 = input[0][18] */
  w18 = arg[0] ? arg[0][18] : 0;
  /* #93: @19 = @2[18] */
  w19 = wr02[18];
  /* #94: @18 = (@18-@19) */
  w18 -= w19;
  /* #95: @19 = sq(@18) */
  w19 = casadi_sq( w18 );
  /* #96: @16 = (@16*@19) */
  w16 *= w19;
  /* #97: @10 = (@10+@16) */
  w10 += w16;
  /* #98: @0 = (@0+@10) */
  w00 += w10;
  /* #99: @10 = 0 */
  w10 = 0.;
  /* #100: @20 = zeros(1x3) */
  casadi_clear(w20, 3);
  /* #101: @21 = zeros(4x1) */
  casadi_clear(w21, 4);
  /* #102: @16 = input[0][12] */
  w16 = arg[0] ? arg[0][12] : 0;
  /* #103: @19 = @2[12] */
  w19 = wr02[12];
  /* #104: @22 = (@16*@19) */
  w22  = (w16*w19);
  /* #105: @23 = input[0][13] */
  w23 = arg[0] ? arg[0][13] : 0;
  /* #106: @24 = @2[13] */
  w24 = wr02[13];
  /* #107: @25 = (@23*@24) */
  w25  = (w23*w24);
  /* #108: @22 = (@22+@25) */
  w22 += w25;
  /* #109: @25 = input[0][14] */
  w25 = arg[0] ? arg[0][14] : 0;
  /* #110: @26 = @2[14] */
  w26 = wr02[14];
  /* #111: @27 = (@25*@26) */
  w27  = (w25*w26);
  /* #112: @22 = (@22+@27) */
  w22 += w27;
  /* #113: @27 = input[0][15] */
  w27 = arg[0] ? arg[0][15] : 0;
  /* #114: @28 = @2[15] */
  w28 = wr02[15];
  /* #115: @29 = (@27*@28) */
  w29  = (w27*w28);
  /* #116: @22 = (@22+@29) */
  w22 += w29;
  /* #117: (@21[0] = @22) */
  for (rr=w21+0, cs=(&w22); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #118: @22 = @2[13] */
  w22 = wr02[13];
  /* #119: @29 = (@16*@22) */
  w29  = (w16*w22);
  /* #120: @30 = @2[12] */
  w30 = wr02[12];
  /* #121: @31 = (@23*@30) */
  w31  = (w23*w30);
  /* #122: @29 = (@29-@31) */
  w29 -= w31;
  /* #123: @31 = @2[14] */
  w31 = wr02[14];
  /* #124: @32 = (@27*@31) */
  w32  = (w27*w31);
  /* #125: @29 = (@29+@32) */
  w29 += w32;
  /* #126: @32 = @2[15] */
  w32 = wr02[15];
  /* #127: @33 = (@25*@32) */
  w33  = (w25*w32);
  /* #128: @29 = (@29-@33) */
  w29 -= w33;
  /* #129: (@21[1] = @29) */
  for (rr=w21+1, cs=(&w29); rr!=w21+2; rr+=1) *rr = *cs++;
  /* #130: @29 = @2[12] */
  w29 = wr02[12];
  /* #131: @33 = (@25*@29) */
  w33  = (w25*w29);
  /* #132: @33 = (-@33) */
  w33 = (- w33 );
  /* #133: @34 = @2[13] */
  w34 = wr02[13];
  /* #134: @35 = (@27*@34) */
  w35  = (w27*w34);
  /* #135: @33 = (@33-@35) */
  w33 -= w35;
  /* #136: @35 = @2[14] */
  w35 = wr02[14];
  /* #137: @36 = (@16*@35) */
  w36  = (w16*w35);
  /* #138: @33 = (@33+@36) */
  w33 += w36;
  /* #139: @36 = @2[15] */
  w36 = wr02[15];
  /* #140: @37 = (@23*@36) */
  w37  = (w23*w36);
  /* #141: @33 = (@33+@37) */
  w33 += w37;
  /* #142: (@21[2] = @33) */
  for (rr=w21+2, cs=(&w33); rr!=w21+3; rr+=1) *rr = *cs++;
  /* #143: @33 = @2[13] */
  w33 = wr02[13];
  /* #144: @25 = (@25*@33) */
  w25 *= w33;
  /* #145: @37 = @2[12] */
  w37 = wr02[12];
  /* #146: @27 = (@27*@37) */
  w27 *= w37;
  /* #147: @25 = (@25-@27) */
  w25 -= w27;
  /* #148: @27 = @2[14] */
  w27 = wr02[14];
  /* #149: @23 = (@23*@27) */
  w23 *= w27;
  /* #150: @25 = (@25-@23) */
  w25 -= w23;
  /* #151: @23 = @2[15] */
  w23 = wr02[15];
  /* #152: @16 = (@16*@23) */
  w16 *= w23;
  /* #153: @25 = (@25+@16) */
  w25 += w16;
  /* #154: (@21[3] = @25) */
  for (rr=w21+3, cs=(&w25); rr!=w21+4; rr+=1) *rr = *cs++;
  /* #155: @25 = @21[0] */
  for (rr=(&w25), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #156: @16 = @21[1] */
  for (rr=(&w16), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #157: @38 = (@25*@16) */
  w38  = (w25*w16);
  /* #158: @39 = @21[2] */
  for (rr=(&w39), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #159: @40 = @21[3] */
  for (rr=(&w40), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #160: @41 = (@39*@40) */
  w41  = (w39*w40);
  /* #161: @38 = (@38-@41) */
  w38 -= w41;
  /* #162: @41 = @21[0] */
  for (rr=(&w41), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #163: @42 = @21[2] */
  for (rr=(&w42), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #164: @43 = (@41*@42) */
  w43  = (w41*w42);
  /* #165: @44 = @21[1] */
  for (rr=(&w44), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #166: @45 = @21[3] */
  for (rr=(&w45), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #167: @46 = (@44*@45) */
  w46  = (w44*w45);
  /* #168: @43 = (@43+@46) */
  w43 += w46;
  /* #169: @46 = @21[3] */
  for (rr=(&w46), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #170: @47 = vertcat(@38, @43, @46) */
  rr=w47;
  *rr++ = w38;
  *rr++ = w43;
  *rr++ = w46;
  /* #171: @38 = 0.001 */
  w38 = 1.0000000000000000e-03;
  /* #172: @43 = @21[0] */
  for (rr=(&w43), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #173: @46 = sq(@43) */
  w46 = casadi_sq( w43 );
  /* #174: @48 = @21[3] */
  for (rr=(&w48), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #175: @49 = sq(@48) */
  w49 = casadi_sq( w48 );
  /* #176: @46 = (@46+@49) */
  w46 += w49;
  /* #177: @38 = (@38+@46) */
  w38 += w46;
  /* #178: @38 = sqrt(@38) */
  w38 = sqrt( w38 );
  /* #179: @47 = (@47/@38) */
  for (i=0, rr=w47; i<3; ++i) (*rr++) /= w38;
  /* #180: @50 = @47' */
  casadi_copy(w47, 3, w50);
  /* #181: @51 = 
  [[5, 0, 0], 
   [0, 5, 0], 
   [0, 0, 10]] */
  wr51 = casadi_c0;
  /* #182: @20 = mac(@50,@51,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w50+j, ct=wr51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #183: @10 = mac(@20,@47,@10) */
  for (i=0, rr=(&w10); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #184: @0 = (@0+@10) */
  w00 += w10;
  /* #185: @10 = 1.5 */
  w10 = 1.5000000000000000e+00;
  /* #186: @46 = input[1][0] */
  w46 = arg[1] ? arg[1][0] : 0;
  /* #187: @49 = @2[19] */
  w49 = wr02[19];
  /* #188: @46 = (@46-@49) */
  w46 -= w49;
  /* #189: @49 = sq(@46) */
  w49 = casadi_sq( w46 );
  /* #190: @10 = (@10*@49) */
  w10 *= w49;
  /* #191: @49 = 1.5 */
  w49 = 1.5000000000000000e+00;
  /* #192: @52 = input[1][1] */
  w52 = arg[1] ? arg[1][1] : 0;
  /* #193: @53 = @2[20] */
  w53 = wr02[20];
  /* #194: @52 = (@52-@53) */
  w52 -= w53;
  /* #195: @53 = sq(@52) */
  w53 = casadi_sq( w52 );
  /* #196: @49 = (@49*@53) */
  w49 *= w53;
  /* #197: @10 = (@10+@49) */
  w10 += w49;
  /* #198: @49 = 1.5 */
  w49 = 1.5000000000000000e+00;
  /* #199: @53 = input[1][2] */
  w53 = arg[1] ? arg[1][2] : 0;
  /* #200: @54 = @2[21] */
  w54 = wr02[21];
  /* #201: @53 = (@53-@54) */
  w53 -= w54;
  /* #202: @54 = sq(@53) */
  w54 = casadi_sq( w53 );
  /* #203: @49 = (@49*@54) */
  w49 *= w54;
  /* #204: @10 = (@10+@49) */
  w10 += w49;
  /* #205: @49 = 1.5 */
  w49 = 1.5000000000000000e+00;
  /* #206: @54 = input[1][3] */
  w54 = arg[1] ? arg[1][3] : 0;
  /* #207: @55 = @2[22] */
  w55 = wr02[22];
  /* #208: @54 = (@54-@55) */
  w54 -= w55;
  /* #209: @55 = sq(@54) */
  w55 = casadi_sq( w54 );
  /* #210: @49 = (@49*@55) */
  w49 *= w55;
  /* #211: @10 = (@10+@49) */
  w10 += w49;
  /* #212: @0 = (@0+@10) */
  w00 += w10;
  /* #213: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #214: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #215: @46 = (2.*@46) */
  w46 = (2.* w46 );
  /* #216: @0 = (@0*@46) */
  w00 *= w46;
  /* #217: output[1][0] = @0 */
  if (res[1]) res[1][0] = w00;
  /* #218: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #219: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #220: @0 = (@0*@52) */
  w00 *= w52;
  /* #221: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #222: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #223: @53 = (2.*@53) */
  w53 = (2.* w53 );
  /* #224: @0 = (@0*@53) */
  w00 *= w53;
  /* #225: output[1][2] = @0 */
  if (res[1]) res[1][2] = w00;
  /* #226: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #227: @54 = (2.*@54) */
  w54 = (2.* w54 );
  /* #228: @0 = (@0*@54) */
  w00 *= w54;
  /* #229: output[1][3] = @0 */
  if (res[1]) res[1][3] = w00;
  /* #230: @0 = 10 */
  w00 = 10.;
  /* #231: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #232: @0 = (@0*@1) */
  w00 *= w01;
  /* #233: output[1][4] = @0 */
  if (res[1]) res[1][4] = w00;
  /* #234: @0 = 10 */
  w00 = 10.;
  /* #235: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #236: @0 = (@0*@4) */
  w00 *= w04;
  /* #237: output[1][5] = @0 */
  if (res[1]) res[1][5] = w00;
  /* #238: @0 = 10 */
  w00 = 10.;
  /* #239: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #240: @0 = (@0*@5) */
  w00 *= w05;
  /* #241: output[1][6] = @0 */
  if (res[1]) res[1][6] = w00;
  /* #242: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #243: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #244: output[1][7] = @3 */
  if (res[1]) res[1][7] = w03;
  /* #245: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #246: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #247: output[1][8] = @6 */
  if (res[1]) res[1][8] = w06;
  /* #248: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #249: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #250: output[1][9] = @7 */
  if (res[1]) res[1][9] = w07;
  /* #251: @7 = 10 */
  w07 = 10.;
  /* #252: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #253: @7 = (@7*@9) */
  w07 *= w09;
  /* #254: output[1][10] = @7 */
  if (res[1]) res[1][10] = w07;
  /* #255: @7 = 10 */
  w07 = 10.;
  /* #256: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #257: @7 = (@7*@11) */
  w07 *= w11;
  /* #258: output[1][11] = @7 */
  if (res[1]) res[1][11] = w07;
  /* #259: @7 = 10 */
  w07 = 10.;
  /* #260: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #261: @7 = (@7*@12) */
  w07 *= w12;
  /* #262: output[1][12] = @7 */
  if (res[1]) res[1][12] = w07;
  /* #263: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #264: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #265: output[1][13] = @8 */
  if (res[1]) res[1][13] = w08;
  /* #266: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #267: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #268: output[1][14] = @13 */
  if (res[1]) res[1][14] = w13;
  /* #269: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #270: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #271: output[1][15] = @14 */
  if (res[1]) res[1][15] = w14;
  /* #272: @21 = zeros(4x1) */
  casadi_clear(w21, 4);
  /* #273: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #274: @50 = (@47/@38) */
  for (i=0, rr=w50, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)/w38);
  /* #275: @50 = (-@50) */
  for (i=0, rr=w50, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #276: @20 = @20' */
  /* #277: @56 = zeros(1x3) */
  casadi_clear(w56, 3);
  /* #278: @47 = @47' */
  /* #279: @57 = @51' */
  for (i=0, rr=w57, cs=wr51; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #280: @56 = mac(@47,@57,@56) */
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #281: @56 = @56' */
  /* #282: @20 = (@20+@56) */
  for (i=0, rr=w20, cs=w56; i<3; ++i) (*rr++) += (*cs++);
  /* #283: @14 = dot(@50, @20) */
  w14 = casadi_dot(3, w50, w20);
  /* #284: @13 = (2.*@38) */
  w13 = (2.* w38 );
  /* #285: @14 = (@14/@13) */
  w14 /= w13;
  /* #286: @48 = (@48*@14) */
  w48 *= w14;
  /* #287: (@21[3] += @48) */
  for (rr=w21+3, cs=(&w48); rr!=w21+4; rr+=1) *rr += *cs++;
  /* #288: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #289: @43 = (@43*@14) */
  w43 *= w14;
  /* #290: (@21[0] += @43) */
  for (rr=w21+0, cs=(&w43); rr!=w21+1; rr+=1) *rr += *cs++;
  /* #291: @20 = (@20/@38) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w38;
  /* #292: {@38, @43, @14} = vertsplit(@20) */
  w38 = w20[0];
  w43 = w20[1];
  w14 = w20[2];
  /* #293: (@21[3] += @14) */
  for (rr=w21+3, cs=(&w14); rr!=w21+4; rr+=1) *rr += *cs++;
  /* #294: @44 = (@44*@43) */
  w44 *= w43;
  /* #295: (@21[3] += @44) */
  for (rr=w21+3, cs=(&w44); rr!=w21+4; rr+=1) *rr += *cs++;
  /* #296: @45 = (@45*@43) */
  w45 *= w43;
  /* #297: (@21[1] += @45) */
  for (rr=w21+1, cs=(&w45); rr!=w21+2; rr+=1) *rr += *cs++;
  /* #298: @41 = (@41*@43) */
  w41 *= w43;
  /* #299: (@21[2] += @41) */
  for (rr=w21+2, cs=(&w41); rr!=w21+3; rr+=1) *rr += *cs++;
  /* #300: @42 = (@42*@43) */
  w42 *= w43;
  /* #301: (@21[0] += @42) */
  for (rr=w21+0, cs=(&w42); rr!=w21+1; rr+=1) *rr += *cs++;
  /* #302: @39 = (@39*@38) */
  w39 *= w38;
  /* #303: @39 = (-@39) */
  w39 = (- w39 );
  /* #304: (@21[3] += @39) */
  for (rr=w21+3, cs=(&w39); rr!=w21+4; rr+=1) *rr += *cs++;
  /* #305: @40 = (@40*@38) */
  w40 *= w38;
  /* #306: @40 = (-@40) */
  w40 = (- w40 );
  /* #307: (@21[2] += @40) */
  for (rr=w21+2, cs=(&w40); rr!=w21+3; rr+=1) *rr += *cs++;
  /* #308: @25 = (@25*@38) */
  w25 *= w38;
  /* #309: (@21[1] += @25) */
  for (rr=w21+1, cs=(&w25); rr!=w21+2; rr+=1) *rr += *cs++;
  /* #310: @16 = (@16*@38) */
  w16 *= w38;
  /* #311: (@21[0] += @16) */
  for (rr=w21+0, cs=(&w16); rr!=w21+1; rr+=1) *rr += *cs++;
  /* #312: @16 = @21[3] */
  for (rr=(&w16), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #313: @23 = (@23*@16) */
  w23 *= w16;
  /* #314: @38 = 0 */
  w38 = 0.;
  /* #315: (@21[3] = @38) */
  for (rr=w21+3, cs=(&w38); rr!=w21+4; rr+=1) *rr = *cs++;
  /* #316: @38 = @21[2] */
  for (rr=(&w38), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #317: @35 = (@35*@38) */
  w35 *= w38;
  /* #318: @23 = (@23+@35) */
  w23 += w35;
  /* #319: @35 = 0 */
  w35 = 0.;
  /* #320: (@21[2] = @35) */
  for (rr=w21+2, cs=(&w35); rr!=w21+3; rr+=1) *rr = *cs++;
  /* #321: @35 = @21[1] */
  for (rr=(&w35), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #322: @22 = (@22*@35) */
  w22 *= w35;
  /* #323: @23 = (@23+@22) */
  w23 += w22;
  /* #324: @22 = 0 */
  w22 = 0.;
  /* #325: (@21[1] = @22) */
  for (rr=w21+1, cs=(&w22); rr!=w21+2; rr+=1) *rr = *cs++;
  /* #326: @22 = @21[0] */
  for (rr=(&w22), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #327: @19 = (@19*@22) */
  w19 *= w22;
  /* #328: @23 = (@23+@19) */
  w23 += w19;
  /* #329: output[1][16] = @23 */
  if (res[1]) res[1][16] = w23;
  /* #330: @36 = (@36*@38) */
  w36 *= w38;
  /* #331: @27 = (@27*@16) */
  w27 *= w16;
  /* #332: @36 = (@36-@27) */
  w36 -= w27;
  /* #333: @30 = (@30*@35) */
  w30 *= w35;
  /* #334: @36 = (@36-@30) */
  w36 -= w30;
  /* #335: @24 = (@24*@22) */
  w24 *= w22;
  /* #336: @36 = (@36+@24) */
  w36 += w24;
  /* #337: output[1][17] = @36 */
  if (res[1]) res[1][17] = w36;
  /* #338: @33 = (@33*@16) */
  w33 *= w16;
  /* #339: @29 = (@29*@38) */
  w29 *= w38;
  /* #340: @33 = (@33-@29) */
  w33 -= w29;
  /* #341: @32 = (@32*@35) */
  w32 *= w35;
  /* #342: @33 = (@33-@32) */
  w33 -= w32;
  /* #343: @26 = (@26*@22) */
  w26 *= w22;
  /* #344: @33 = (@33+@26) */
  w33 += w26;
  /* #345: output[1][18] = @33 */
  if (res[1]) res[1][18] = w33;
  /* #346: @34 = (@34*@38) */
  w34 *= w38;
  /* #347: @34 = (-@34) */
  w34 = (- w34 );
  /* #348: @37 = (@37*@16) */
  w37 *= w16;
  /* #349: @34 = (@34-@37) */
  w34 -= w37;
  /* #350: @31 = (@31*@35) */
  w31 *= w35;
  /* #351: @34 = (@34+@31) */
  w34 += w31;
  /* #352: @28 = (@28*@22) */
  w28 *= w22;
  /* #353: @34 = (@34+@28) */
  w34 += w28;
  /* #354: output[1][19] = @34 */
  if (res[1]) res[1][19] = w34;
  /* #355: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #356: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #357: @34 = (@34*@15) */
  w34 *= w15;
  /* #358: output[1][20] = @34 */
  if (res[1]) res[1][20] = w34;
  /* #359: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #360: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #361: @34 = (@34*@17) */
  w34 *= w17;
  /* #362: output[1][21] = @34 */
  if (res[1]) res[1][21] = w34;
  /* #363: @34 = 0.2 */
  w34 = 2.0000000000000001e-01;
  /* #364: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #365: @34 = (@34*@18) */
  w34 *= w18;
  /* #366: output[1][22] = @34 */
  if (res[1]) res[1][22] = w34;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 108;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 108*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
