class GroupNames:
    TRAJS = "trajs"

class DatasetKeys:
    NAME = "name"
    TIME = "time"
    PATH = "path"
    DEPTH_TIME = "depth_time"
    PAYLOAD_POS = "payload_pos"
    PAYLOAD_VEL = "payload_vel"
    ROBOT_POS = "robot_pos"
    ROBOT_VEL = "robot_vel"
    ROBOT_QUAT = "robot_quat"
    U = "u"
    FUTURE_ROBOT_POS = "future_robot_pos"
    FUTURE_ROBOT_POS_WORLD = "future_robot_pos_world"
    FUTURE_PAYLOAD_POS = "future_payload_pos"
    FUTURE_PAYLOAD_POS_WORLD = "future_payload_pos_world"
    FUTURE_QUATERNION = "future_quaternion"
    FUTURE_ROBOT_VEL = "future_robot_vel"
    FUTURE_PAYLOAD_VEL = "future_payload_vel"
    FUTURE_ROT_MAT = "future_rot_mat"
    DEPTH = "depth"
    YAML_FILE = "yaml_file"
    ROBOT_GOAL = "robot_goal"
    ROBOT_GOAL_RELATIVE = "robot_goal_relative"
    YAML_FILE_NAME = "yaml_file_name"
    SOL_X = "sol_x"
    SOL_U = "sol_u"
    SOL_QUAD_X = "sol_quad_x"
    PARAMS = "params"
    SOL_PAYLOAD_RPY = "sol_payload_rpy"
    SOL_QUAD_QUAT = "sol_quad_quat"
    ROT_MAT = "rot_mat"

class AttrKeys:
    T = "T"
    STEM = "stem"
    YAML_FILE_NAME = "yaml_file_name"
    NUM_TRAJS = "num_trajs"
    CSV_SUBDIRECTORY = "csv_subdirectory"
    CSV_FILEPATH = "csv_filepath"