/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {19, 1, 1};
static const casadi_int casadi_s1[3] = {0, 0, 1};
static const casadi_int casadi_s2[3] = {23, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_c0[9] = 
  {5., 0., 0., 0., 5., 0., 0., 0.,
  100.};

static const casadi_real casadi_zeros[23] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* quadrotor_cost_ext_cost_e_fun_jac:(i0[19],i1[],i2[],i3[23])->(o0,o1[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+43, *w21=w+46, w22, w23;
  casadi_real w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  casadi_real w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47;
  casadi_real *w48=w+76, w49, w50, *w51=w+81, *w53=w+93, *w54=w+96;
  const casadi_real *cr, *cs, *ct, *wr02, *wr52;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = input[0][0] */
  w01 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[3][0] */
  wr02 = arg[3] ? arg[3] : casadi_zeros;
  /* #3: @3 = @2[0] */
  w03 = wr02[0];
  /* #4: @1 = (@1-@3) */
  w01 -= w03;
  /* #5: @3 = sq(@1) */
  w03 = casadi_sq( w01 );
  /* #6: @0 = (@0*@3) */
  w00 *= w03;
  /* #7: @3 = 10 */
  w03 = 10.;
  /* #8: @4 = input[0][1] */
  w04 = arg[0] ? arg[0][1] : 0;
  /* #9: @5 = @2[1] */
  w05 = wr02[1];
  /* #10: @4 = (@4-@5) */
  w04 -= w05;
  /* #11: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #12: @3 = (@3*@5) */
  w03 *= w05;
  /* #13: @0 = (@0+@3) */
  w00 += w03;
  /* #14: @3 = 10 */
  w03 = 10.;
  /* #15: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #16: @6 = @2[2] */
  w06 = wr02[2];
  /* #17: @5 = (@5-@6) */
  w05 -= w06;
  /* #18: @6 = sq(@5) */
  w06 = casadi_sq( w05 );
  /* #19: @3 = (@3*@6) */
  w03 *= w06;
  /* #20: @0 = (@0+@3) */
  w00 += w03;
  /* #21: @3 = 10 */
  w03 = 10.;
  /* #22: @6 = input[0][3] */
  w06 = arg[0] ? arg[0][3] : 0;
  /* #23: @7 = @2[3] */
  w07 = wr02[3];
  /* #24: @6 = (@6-@7) */
  w06 -= w07;
  /* #25: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #26: @3 = (@3*@7) */
  w03 *= w07;
  /* #27: @0 = (@0+@3) */
  w00 += w03;
  /* #28: @3 = 10 */
  w03 = 10.;
  /* #29: @7 = input[0][4] */
  w07 = arg[0] ? arg[0][4] : 0;
  /* #30: @8 = @2[4] */
  w08 = wr02[4];
  /* #31: @7 = (@7-@8) */
  w07 -= w08;
  /* #32: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #33: @3 = (@3*@8) */
  w03 *= w08;
  /* #34: @0 = (@0+@3) */
  w00 += w03;
  /* #35: @3 = 10 */
  w03 = 10.;
  /* #36: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][5] : 0;
  /* #37: @9 = @2[5] */
  w09 = wr02[5];
  /* #38: @8 = (@8-@9) */
  w08 -= w09;
  /* #39: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #40: @3 = (@3*@9) */
  w03 *= w09;
  /* #41: @0 = (@0+@3) */
  w00 += w03;
  /* #42: @3 = 10 */
  w03 = 10.;
  /* #43: @9 = input[0][6] */
  w09 = arg[0] ? arg[0][6] : 0;
  /* #44: @10 = @2[6] */
  w10 = wr02[6];
  /* #45: @9 = (@9-@10) */
  w09 -= w10;
  /* #46: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #47: @3 = (@3*@10) */
  w03 *= w10;
  /* #48: @10 = 10 */
  w10 = 10.;
  /* #49: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #50: @12 = @2[7] */
  w12 = wr02[7];
  /* #51: @11 = (@11-@12) */
  w11 -= w12;
  /* #52: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #53: @10 = (@10*@12) */
  w10 *= w12;
  /* #54: @3 = (@3+@10) */
  w03 += w10;
  /* #55: @10 = 10 */
  w10 = 10.;
  /* #56: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #57: @13 = @2[8] */
  w13 = wr02[8];
  /* #58: @12 = (@12-@13) */
  w12 -= w13;
  /* #59: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #60: @10 = (@10*@13) */
  w10 *= w13;
  /* #61: @3 = (@3+@10) */
  w03 += w10;
  /* #62: @0 = (@0+@3) */
  w00 += w03;
  /* #63: @3 = 10 */
  w03 = 10.;
  /* #64: @10 = input[0][9] */
  w10 = arg[0] ? arg[0][9] : 0;
  /* #65: @13 = @2[9] */
  w13 = wr02[9];
  /* #66: @10 = (@10-@13) */
  w10 -= w13;
  /* #67: @13 = sq(@10) */
  w13 = casadi_sq( w10 );
  /* #68: @3 = (@3*@13) */
  w03 *= w13;
  /* #69: @13 = 10 */
  w13 = 10.;
  /* #70: @14 = input[0][10] */
  w14 = arg[0] ? arg[0][10] : 0;
  /* #71: @15 = @2[10] */
  w15 = wr02[10];
  /* #72: @14 = (@14-@15) */
  w14 -= w15;
  /* #73: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #74: @13 = (@13*@15) */
  w13 *= w15;
  /* #75: @3 = (@3+@13) */
  w03 += w13;
  /* #76: @13 = 10 */
  w13 = 10.;
  /* #77: @15 = input[0][11] */
  w15 = arg[0] ? arg[0][11] : 0;
  /* #78: @16 = @2[11] */
  w16 = wr02[11];
  /* #79: @15 = (@15-@16) */
  w15 -= w16;
  /* #80: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #81: @13 = (@13*@16) */
  w13 *= w16;
  /* #82: @3 = (@3+@13) */
  w03 += w13;
  /* #83: @0 = (@0+@3) */
  w00 += w03;
  /* #84: @3 = @2[22] */
  w03 = wr02[22];
  /* #85: @13 = input[0][16] */
  w13 = arg[0] ? arg[0][16] : 0;
  /* #86: @16 = @2[16] */
  w16 = wr02[16];
  /* #87: @13 = (@13-@16) */
  w13 -= w16;
  /* #88: @16 = sq(@13) */
  w16 = casadi_sq( w13 );
  /* #89: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #90: @17 = input[0][17] */
  w17 = arg[0] ? arg[0][17] : 0;
  /* #91: @18 = @2[17] */
  w18 = wr02[17];
  /* #92: @17 = (@17-@18) */
  w17 -= w18;
  /* #93: @18 = sq(@17) */
  w18 = casadi_sq( w17 );
  /* #94: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #95: @16 = (@16+@18) */
  w16 += w18;
  /* #96: @18 = input[0][18] */
  w18 = arg[0] ? arg[0][18] : 0;
  /* #97: @19 = @2[18] */
  w19 = wr02[18];
  /* #98: @18 = (@18-@19) */
  w18 -= w19;
  /* #99: @19 = sq(@18) */
  w19 = casadi_sq( w18 );
  /* #100: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #101: @16 = (@16+@19) */
  w16 += w19;
  /* #102: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #103: @0 = (@0+@16) */
  w00 += w16;
  /* #104: @16 = 0 */
  w16 = 0.;
  /* #105: @20 = zeros(1x3) */
  casadi_clear(w20, 3);
  /* #106: @21 = zeros(4x1) */
  casadi_clear(w21, 4);
  /* #107: @19 = input[0][12] */
  w19 = arg[0] ? arg[0][12] : 0;
  /* #108: @22 = @2[12] */
  w22 = wr02[12];
  /* #109: @23 = (@19*@22) */
  w23  = (w19*w22);
  /* #110: @24 = input[0][13] */
  w24 = arg[0] ? arg[0][13] : 0;
  /* #111: @25 = @2[13] */
  w25 = wr02[13];
  /* #112: @26 = (@24*@25) */
  w26  = (w24*w25);
  /* #113: @23 = (@23+@26) */
  w23 += w26;
  /* #114: @26 = input[0][14] */
  w26 = arg[0] ? arg[0][14] : 0;
  /* #115: @27 = @2[14] */
  w27 = wr02[14];
  /* #116: @28 = (@26*@27) */
  w28  = (w26*w27);
  /* #117: @23 = (@23+@28) */
  w23 += w28;
  /* #118: @28 = input[0][15] */
  w28 = arg[0] ? arg[0][15] : 0;
  /* #119: @29 = @2[15] */
  w29 = wr02[15];
  /* #120: @30 = (@28*@29) */
  w30  = (w28*w29);
  /* #121: @23 = (@23+@30) */
  w23 += w30;
  /* #122: (@21[0] = @23) */
  for (rr=w21+0, cs=(&w23); rr!=w21+1; rr+=1) *rr = *cs++;
  /* #123: @23 = @2[13] */
  w23 = wr02[13];
  /* #124: @30 = (@19*@23) */
  w30  = (w19*w23);
  /* #125: @31 = @2[12] */
  w31 = wr02[12];
  /* #126: @32 = (@24*@31) */
  w32  = (w24*w31);
  /* #127: @30 = (@30-@32) */
  w30 -= w32;
  /* #128: @32 = @2[14] */
  w32 = wr02[14];
  /* #129: @33 = (@28*@32) */
  w33  = (w28*w32);
  /* #130: @30 = (@30+@33) */
  w30 += w33;
  /* #131: @33 = @2[15] */
  w33 = wr02[15];
  /* #132: @34 = (@26*@33) */
  w34  = (w26*w33);
  /* #133: @30 = (@30-@34) */
  w30 -= w34;
  /* #134: (@21[1] = @30) */
  for (rr=w21+1, cs=(&w30); rr!=w21+2; rr+=1) *rr = *cs++;
  /* #135: @30 = @2[12] */
  w30 = wr02[12];
  /* #136: @34 = (@26*@30) */
  w34  = (w26*w30);
  /* #137: @34 = (-@34) */
  w34 = (- w34 );
  /* #138: @35 = @2[13] */
  w35 = wr02[13];
  /* #139: @36 = (@28*@35) */
  w36  = (w28*w35);
  /* #140: @34 = (@34-@36) */
  w34 -= w36;
  /* #141: @36 = @2[14] */
  w36 = wr02[14];
  /* #142: @37 = (@19*@36) */
  w37  = (w19*w36);
  /* #143: @34 = (@34+@37) */
  w34 += w37;
  /* #144: @37 = @2[15] */
  w37 = wr02[15];
  /* #145: @38 = (@24*@37) */
  w38  = (w24*w37);
  /* #146: @34 = (@34+@38) */
  w34 += w38;
  /* #147: (@21[2] = @34) */
  for (rr=w21+2, cs=(&w34); rr!=w21+3; rr+=1) *rr = *cs++;
  /* #148: @34 = @2[13] */
  w34 = wr02[13];
  /* #149: @26 = (@26*@34) */
  w26 *= w34;
  /* #150: @38 = @2[12] */
  w38 = wr02[12];
  /* #151: @28 = (@28*@38) */
  w28 *= w38;
  /* #152: @26 = (@26-@28) */
  w26 -= w28;
  /* #153: @28 = @2[14] */
  w28 = wr02[14];
  /* #154: @24 = (@24*@28) */
  w24 *= w28;
  /* #155: @26 = (@26-@24) */
  w26 -= w24;
  /* #156: @24 = @2[15] */
  w24 = wr02[15];
  /* #157: @19 = (@19*@24) */
  w19 *= w24;
  /* #158: @26 = (@26+@19) */
  w26 += w19;
  /* #159: (@21[3] = @26) */
  for (rr=w21+3, cs=(&w26); rr!=w21+4; rr+=1) *rr = *cs++;
  /* #160: @26 = @21[0] */
  for (rr=(&w26), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #161: @19 = @21[1] */
  for (rr=(&w19), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #162: @39 = (@26*@19) */
  w39  = (w26*w19);
  /* #163: @40 = @21[2] */
  for (rr=(&w40), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #164: @41 = @21[3] */
  for (rr=(&w41), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #165: @42 = (@40*@41) */
  w42  = (w40*w41);
  /* #166: @39 = (@39-@42) */
  w39 -= w42;
  /* #167: @42 = @21[0] */
  for (rr=(&w42), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #168: @43 = @21[2] */
  for (rr=(&w43), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #169: @44 = (@42*@43) */
  w44  = (w42*w43);
  /* #170: @45 = @21[1] */
  for (rr=(&w45), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #171: @46 = @21[3] */
  for (rr=(&w46), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #172: @47 = (@45*@46) */
  w47  = (w45*w46);
  /* #173: @44 = (@44+@47) */
  w44 += w47;
  /* #174: @47 = @21[3] */
  for (rr=(&w47), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #175: @48 = vertcat(@39, @44, @47) */
  rr=w48;
  *rr++ = w39;
  *rr++ = w44;
  *rr++ = w47;
  /* #176: @39 = 0.001 */
  w39 = 1.0000000000000000e-03;
  /* #177: @44 = @21[0] */
  for (rr=(&w44), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #178: @47 = sq(@44) */
  w47 = casadi_sq( w44 );
  /* #179: @49 = @21[3] */
  for (rr=(&w49), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #180: @50 = sq(@49) */
  w50 = casadi_sq( w49 );
  /* #181: @47 = (@47+@50) */
  w47 += w50;
  /* #182: @39 = (@39+@47) */
  w39 += w47;
  /* #183: @39 = sqrt(@39) */
  w39 = sqrt( w39 );
  /* #184: @48 = (@48/@39) */
  for (i=0, rr=w48; i<3; ++i) (*rr++) /= w39;
  /* #185: @51 = @48' */
  casadi_copy(w48, 3, w51);
  /* #186: @52 = 
  [[5, 0, 0], 
   [0, 5, 0], 
   [0, 0, 100]] */
  wr52 = casadi_c0;
  /* #187: @20 = mac(@51,@52,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w51+j, ct=wr52+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #188: @16 = mac(@20,@48,@16) */
  for (i=0, rr=(&w16); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w20+j, ct=w48+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #189: @0 = (@0+@16) */
  w00 += w16;
  /* #190: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #191: @0 = 10 */
  w00 = 10.;
  /* #192: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #193: @0 = (@0*@1) */
  w00 *= w01;
  /* #194: output[1][0] = @0 */
  if (res[1]) res[1][0] = w00;
  /* #195: @0 = 10 */
  w00 = 10.;
  /* #196: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #197: @0 = (@0*@4) */
  w00 *= w04;
  /* #198: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #199: @0 = 10 */
  w00 = 10.;
  /* #200: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #201: @0 = (@0*@5) */
  w00 *= w05;
  /* #202: output[1][2] = @0 */
  if (res[1]) res[1][2] = w00;
  /* #203: @0 = 10 */
  w00 = 10.;
  /* #204: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #205: @0 = (@0*@6) */
  w00 *= w06;
  /* #206: output[1][3] = @0 */
  if (res[1]) res[1][3] = w00;
  /* #207: @0 = 10 */
  w00 = 10.;
  /* #208: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #209: @0 = (@0*@7) */
  w00 *= w07;
  /* #210: output[1][4] = @0 */
  if (res[1]) res[1][4] = w00;
  /* #211: @0 = 10 */
  w00 = 10.;
  /* #212: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #213: @0 = (@0*@8) */
  w00 *= w08;
  /* #214: output[1][5] = @0 */
  if (res[1]) res[1][5] = w00;
  /* #215: @0 = 10 */
  w00 = 10.;
  /* #216: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #217: @0 = (@0*@9) */
  w00 *= w09;
  /* #218: output[1][6] = @0 */
  if (res[1]) res[1][6] = w00;
  /* #219: @0 = 10 */
  w00 = 10.;
  /* #220: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #221: @0 = (@0*@11) */
  w00 *= w11;
  /* #222: output[1][7] = @0 */
  if (res[1]) res[1][7] = w00;
  /* #223: @0 = 10 */
  w00 = 10.;
  /* #224: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #225: @0 = (@0*@12) */
  w00 *= w12;
  /* #226: output[1][8] = @0 */
  if (res[1]) res[1][8] = w00;
  /* #227: @0 = 10 */
  w00 = 10.;
  /* #228: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #229: @0 = (@0*@10) */
  w00 *= w10;
  /* #230: output[1][9] = @0 */
  if (res[1]) res[1][9] = w00;
  /* #231: @0 = 10 */
  w00 = 10.;
  /* #232: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #233: @0 = (@0*@14) */
  w00 *= w14;
  /* #234: output[1][10] = @0 */
  if (res[1]) res[1][10] = w00;
  /* #235: @0 = 10 */
  w00 = 10.;
  /* #236: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #237: @0 = (@0*@15) */
  w00 *= w15;
  /* #238: output[1][11] = @0 */
  if (res[1]) res[1][11] = w00;
  /* #239: @21 = zeros(4x1) */
  casadi_clear(w21, 4);
  /* #240: @49 = (2.*@49) */
  w49 = (2.* w49 );
  /* #241: @51 = (@48/@39) */
  for (i=0, rr=w51, cr=w48; i<3; ++i) (*rr++)  = ((*cr++)/w39);
  /* #242: @51 = (-@51) */
  for (i=0, rr=w51, cs=w51; i<3; ++i) *rr++ = (- *cs++ );
  /* #243: @20 = @20' */
  /* #244: @53 = zeros(1x3) */
  casadi_clear(w53, 3);
  /* #245: @48 = @48' */
  /* #246: @54 = @52' */
  for (i=0, rr=w54, cs=wr52; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #247: @53 = mac(@48,@54,@53) */
  for (i=0, rr=w53; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w48+j, ct=w54+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #248: @53 = @53' */
  /* #249: @20 = (@20+@53) */
  for (i=0, rr=w20, cs=w53; i<3; ++i) (*rr++) += (*cs++);
  /* #250: @0 = dot(@51, @20) */
  w00 = casadi_dot(3, w51, w20);
  /* #251: @15 = (2.*@39) */
  w15 = (2.* w39 );
  /* #252: @0 = (@0/@15) */
  w00 /= w15;
  /* #253: @49 = (@49*@0) */
  w49 *= w00;
  /* #254: (@21[3] += @49) */
  for (rr=w21+3, cs=(&w49); rr!=w21+4; rr+=1) *rr += *cs++;
  /* #255: @44 = (2.*@44) */
  w44 = (2.* w44 );
  /* #256: @44 = (@44*@0) */
  w44 *= w00;
  /* #257: (@21[0] += @44) */
  for (rr=w21+0, cs=(&w44); rr!=w21+1; rr+=1) *rr += *cs++;
  /* #258: @20 = (@20/@39) */
  for (i=0, rr=w20; i<3; ++i) (*rr++) /= w39;
  /* #259: {@39, @44, @0} = vertsplit(@20) */
  w39 = w20[0];
  w44 = w20[1];
  w00 = w20[2];
  /* #260: (@21[3] += @0) */
  for (rr=w21+3, cs=(&w00); rr!=w21+4; rr+=1) *rr += *cs++;
  /* #261: @45 = (@45*@44) */
  w45 *= w44;
  /* #262: (@21[3] += @45) */
  for (rr=w21+3, cs=(&w45); rr!=w21+4; rr+=1) *rr += *cs++;
  /* #263: @46 = (@46*@44) */
  w46 *= w44;
  /* #264: (@21[1] += @46) */
  for (rr=w21+1, cs=(&w46); rr!=w21+2; rr+=1) *rr += *cs++;
  /* #265: @42 = (@42*@44) */
  w42 *= w44;
  /* #266: (@21[2] += @42) */
  for (rr=w21+2, cs=(&w42); rr!=w21+3; rr+=1) *rr += *cs++;
  /* #267: @43 = (@43*@44) */
  w43 *= w44;
  /* #268: (@21[0] += @43) */
  for (rr=w21+0, cs=(&w43); rr!=w21+1; rr+=1) *rr += *cs++;
  /* #269: @40 = (@40*@39) */
  w40 *= w39;
  /* #270: @40 = (-@40) */
  w40 = (- w40 );
  /* #271: (@21[3] += @40) */
  for (rr=w21+3, cs=(&w40); rr!=w21+4; rr+=1) *rr += *cs++;
  /* #272: @41 = (@41*@39) */
  w41 *= w39;
  /* #273: @41 = (-@41) */
  w41 = (- w41 );
  /* #274: (@21[2] += @41) */
  for (rr=w21+2, cs=(&w41); rr!=w21+3; rr+=1) *rr += *cs++;
  /* #275: @26 = (@26*@39) */
  w26 *= w39;
  /* #276: (@21[1] += @26) */
  for (rr=w21+1, cs=(&w26); rr!=w21+2; rr+=1) *rr += *cs++;
  /* #277: @19 = (@19*@39) */
  w19 *= w39;
  /* #278: (@21[0] += @19) */
  for (rr=w21+0, cs=(&w19); rr!=w21+1; rr+=1) *rr += *cs++;
  /* #279: @19 = @21[3] */
  for (rr=(&w19), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #280: @24 = (@24*@19) */
  w24 *= w19;
  /* #281: @39 = 0 */
  w39 = 0.;
  /* #282: (@21[3] = @39) */
  for (rr=w21+3, cs=(&w39); rr!=w21+4; rr+=1) *rr = *cs++;
  /* #283: @39 = @21[2] */
  for (rr=(&w39), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #284: @36 = (@36*@39) */
  w36 *= w39;
  /* #285: @24 = (@24+@36) */
  w24 += w36;
  /* #286: @36 = 0 */
  w36 = 0.;
  /* #287: (@21[2] = @36) */
  for (rr=w21+2, cs=(&w36); rr!=w21+3; rr+=1) *rr = *cs++;
  /* #288: @36 = @21[1] */
  for (rr=(&w36), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #289: @23 = (@23*@36) */
  w23 *= w36;
  /* #290: @24 = (@24+@23) */
  w24 += w23;
  /* #291: @23 = 0 */
  w23 = 0.;
  /* #292: (@21[1] = @23) */
  for (rr=w21+1, cs=(&w23); rr!=w21+2; rr+=1) *rr = *cs++;
  /* #293: @23 = @21[0] */
  for (rr=(&w23), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #294: @22 = (@22*@23) */
  w22 *= w23;
  /* #295: @24 = (@24+@22) */
  w24 += w22;
  /* #296: output[1][12] = @24 */
  if (res[1]) res[1][12] = w24;
  /* #297: @37 = (@37*@39) */
  w37 *= w39;
  /* #298: @28 = (@28*@19) */
  w28 *= w19;
  /* #299: @37 = (@37-@28) */
  w37 -= w28;
  /* #300: @31 = (@31*@36) */
  w31 *= w36;
  /* #301: @37 = (@37-@31) */
  w37 -= w31;
  /* #302: @25 = (@25*@23) */
  w25 *= w23;
  /* #303: @37 = (@37+@25) */
  w37 += w25;
  /* #304: output[1][13] = @37 */
  if (res[1]) res[1][13] = w37;
  /* #305: @34 = (@34*@19) */
  w34 *= w19;
  /* #306: @30 = (@30*@39) */
  w30 *= w39;
  /* #307: @34 = (@34-@30) */
  w34 -= w30;
  /* #308: @33 = (@33*@36) */
  w33 *= w36;
  /* #309: @34 = (@34-@33) */
  w34 -= w33;
  /* #310: @27 = (@27*@23) */
  w27 *= w23;
  /* #311: @34 = (@34+@27) */
  w34 += w27;
  /* #312: output[1][14] = @34 */
  if (res[1]) res[1][14] = w34;
  /* #313: @35 = (@35*@39) */
  w35 *= w39;
  /* #314: @35 = (-@35) */
  w35 = (- w35 );
  /* #315: @38 = (@38*@19) */
  w38 *= w19;
  /* #316: @35 = (@35-@38) */
  w35 -= w38;
  /* #317: @32 = (@32*@36) */
  w32 *= w36;
  /* #318: @35 = (@35+@32) */
  w35 += w32;
  /* #319: @29 = (@29*@23) */
  w29 *= w23;
  /* #320: @35 = (@35+@29) */
  w35 += w29;
  /* #321: output[1][15] = @35 */
  if (res[1]) res[1][15] = w35;
  /* #322: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #323: @35 = (2.*@3) */
  w35 = (2.* w03 );
  /* #324: @13 = (@13*@35) */
  w13 *= w35;
  /* #325: output[1][16] = @13 */
  if (res[1]) res[1][16] = w13;
  /* #326: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #327: @13 = (2.*@3) */
  w13 = (2.* w03 );
  /* #328: @17 = (@17*@13) */
  w17 *= w13;
  /* #329: output[1][17] = @17 */
  if (res[1]) res[1][17] = w17;
  /* #330: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #331: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #332: @18 = (@18*@3) */
  w18 *= w03;
  /* #333: output[1][18] = @18 */
  if (res[1]) res[1][18] = w18;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 105;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 105*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
