/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[3] = {19, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {23, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_c0[9] = 
  {5., 0., 0., 0., 5., 0., 0., 0.,
  100.};

static const casadi_real casadi_zeros[23] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* quadrotor_cost_ext_cost_fun_jac:(i0[19],i1[4],i2[],i3[23])->(o0,o1[23]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, *w19=w+42, *w20=w+45, w21, w22, w23;
  casadi_real w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  casadi_real w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, *w47=w+75;
  casadi_real w48, w49, *w50=w+80, w52, w53, w54, w55, *w56=w+96, *w57=w+99;
  const casadi_real *cr, *cs, *ct, *wr02, *wr51;
  /* #0: @0 = 10 */
  w00 = 10.;
  /* #1: @1 = input[0][0] */
  w01 = arg[0] ? arg[0][0] : 0;
  /* #2: @2 = input[3][0] */
  wr02 = arg[3] ? arg[3] : casadi_zeros;
  /* #3: @3 = @2[0] */
  w03 = wr02[0];
  /* #4: @1 = (@1-@3) */
  w01 -= w03;
  /* #5: @3 = sq(@1) */
  w03 = casadi_sq( w01 );
  /* #6: @0 = (@0*@3) */
  w00 *= w03;
  /* #7: @3 = 10 */
  w03 = 10.;
  /* #8: @4 = input[0][1] */
  w04 = arg[0] ? arg[0][1] : 0;
  /* #9: @5 = @2[1] */
  w05 = wr02[1];
  /* #10: @4 = (@4-@5) */
  w04 -= w05;
  /* #11: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #12: @3 = (@3*@5) */
  w03 *= w05;
  /* #13: @0 = (@0+@3) */
  w00 += w03;
  /* #14: @3 = 10 */
  w03 = 10.;
  /* #15: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #16: @6 = @2[2] */
  w06 = wr02[2];
  /* #17: @5 = (@5-@6) */
  w05 -= w06;
  /* #18: @6 = sq(@5) */
  w06 = casadi_sq( w05 );
  /* #19: @3 = (@3*@6) */
  w03 *= w06;
  /* #20: @0 = (@0+@3) */
  w00 += w03;
  /* #21: @3 = 10 */
  w03 = 10.;
  /* #22: @6 = input[0][3] */
  w06 = arg[0] ? arg[0][3] : 0;
  /* #23: @7 = @2[3] */
  w07 = wr02[3];
  /* #24: @6 = (@6-@7) */
  w06 -= w07;
  /* #25: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #26: @3 = (@3*@7) */
  w03 *= w07;
  /* #27: @0 = (@0+@3) */
  w00 += w03;
  /* #28: @3 = 10 */
  w03 = 10.;
  /* #29: @7 = input[0][4] */
  w07 = arg[0] ? arg[0][4] : 0;
  /* #30: @8 = @2[4] */
  w08 = wr02[4];
  /* #31: @7 = (@7-@8) */
  w07 -= w08;
  /* #32: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #33: @3 = (@3*@8) */
  w03 *= w08;
  /* #34: @0 = (@0+@3) */
  w00 += w03;
  /* #35: @3 = 10 */
  w03 = 10.;
  /* #36: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][5] : 0;
  /* #37: @9 = @2[5] */
  w09 = wr02[5];
  /* #38: @8 = (@8-@9) */
  w08 -= w09;
  /* #39: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #40: @3 = (@3*@9) */
  w03 *= w09;
  /* #41: @0 = (@0+@3) */
  w00 += w03;
  /* #42: @3 = 10 */
  w03 = 10.;
  /* #43: @9 = input[0][6] */
  w09 = arg[0] ? arg[0][6] : 0;
  /* #44: @10 = @2[6] */
  w10 = wr02[6];
  /* #45: @9 = (@9-@10) */
  w09 -= w10;
  /* #46: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #47: @3 = (@3*@10) */
  w03 *= w10;
  /* #48: @10 = 10 */
  w10 = 10.;
  /* #49: @11 = input[0][7] */
  w11 = arg[0] ? arg[0][7] : 0;
  /* #50: @12 = @2[7] */
  w12 = wr02[7];
  /* #51: @11 = (@11-@12) */
  w11 -= w12;
  /* #52: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #53: @10 = (@10*@12) */
  w10 *= w12;
  /* #54: @3 = (@3+@10) */
  w03 += w10;
  /* #55: @10 = 10 */
  w10 = 10.;
  /* #56: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #57: @13 = @2[8] */
  w13 = wr02[8];
  /* #58: @12 = (@12-@13) */
  w12 -= w13;
  /* #59: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #60: @10 = (@10*@13) */
  w10 *= w13;
  /* #61: @3 = (@3+@10) */
  w03 += w10;
  /* #62: @0 = (@0+@3) */
  w00 += w03;
  /* #63: @3 = 10 */
  w03 = 10.;
  /* #64: @10 = input[0][9] */
  w10 = arg[0] ? arg[0][9] : 0;
  /* #65: @13 = @2[9] */
  w13 = wr02[9];
  /* #66: @10 = (@10-@13) */
  w10 -= w13;
  /* #67: @13 = sq(@10) */
  w13 = casadi_sq( w10 );
  /* #68: @3 = (@3*@13) */
  w03 *= w13;
  /* #69: @13 = 10 */
  w13 = 10.;
  /* #70: @14 = input[0][10] */
  w14 = arg[0] ? arg[0][10] : 0;
  /* #71: @15 = @2[10] */
  w15 = wr02[10];
  /* #72: @14 = (@14-@15) */
  w14 -= w15;
  /* #73: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #74: @13 = (@13*@15) */
  w13 *= w15;
  /* #75: @3 = (@3+@13) */
  w03 += w13;
  /* #76: @13 = 10 */
  w13 = 10.;
  /* #77: @15 = input[0][11] */
  w15 = arg[0] ? arg[0][11] : 0;
  /* #78: @16 = @2[11] */
  w16 = wr02[11];
  /* #79: @15 = (@15-@16) */
  w15 -= w16;
  /* #80: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #81: @13 = (@13*@16) */
  w13 *= w16;
  /* #82: @3 = (@3+@13) */
  w03 += w13;
  /* #83: @0 = (@0+@3) */
  w00 += w03;
  /* #84: @3 = input[0][16] */
  w03 = arg[0] ? arg[0][16] : 0;
  /* #85: @13 = @2[16] */
  w13 = wr02[16];
  /* #86: @3 = (@3-@13) */
  w03 -= w13;
  /* #87: @13 = sq(@3) */
  w13 = casadi_sq( w03 );
  /* #88: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #89: @16 = input[0][17] */
  w16 = arg[0] ? arg[0][17] : 0;
  /* #90: @17 = @2[17] */
  w17 = wr02[17];
  /* #91: @16 = (@16-@17) */
  w16 -= w17;
  /* #92: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #93: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #94: @13 = (@13+@17) */
  w13 += w17;
  /* #95: @17 = input[0][18] */
  w17 = arg[0] ? arg[0][18] : 0;
  /* #96: @18 = @2[18] */
  w18 = wr02[18];
  /* #97: @17 = (@17-@18) */
  w17 -= w18;
  /* #98: @18 = sq(@17) */
  w18 = casadi_sq( w17 );
  /* #99: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #100: @13 = (@13+@18) */
  w13 += w18;
  /* #101: @0 = (@0+@13) */
  w00 += w13;
  /* #102: @13 = 0 */
  w13 = 0.;
  /* #103: @19 = zeros(1x3) */
  casadi_clear(w19, 3);
  /* #104: @20 = zeros(4x1) */
  casadi_clear(w20, 4);
  /* #105: @18 = input[0][12] */
  w18 = arg[0] ? arg[0][12] : 0;
  /* #106: @21 = @2[12] */
  w21 = wr02[12];
  /* #107: @22 = (@18*@21) */
  w22  = (w18*w21);
  /* #108: @23 = input[0][13] */
  w23 = arg[0] ? arg[0][13] : 0;
  /* #109: @24 = @2[13] */
  w24 = wr02[13];
  /* #110: @25 = (@23*@24) */
  w25  = (w23*w24);
  /* #111: @22 = (@22+@25) */
  w22 += w25;
  /* #112: @25 = input[0][14] */
  w25 = arg[0] ? arg[0][14] : 0;
  /* #113: @26 = @2[14] */
  w26 = wr02[14];
  /* #114: @27 = (@25*@26) */
  w27  = (w25*w26);
  /* #115: @22 = (@22+@27) */
  w22 += w27;
  /* #116: @27 = input[0][15] */
  w27 = arg[0] ? arg[0][15] : 0;
  /* #117: @28 = @2[15] */
  w28 = wr02[15];
  /* #118: @29 = (@27*@28) */
  w29  = (w27*w28);
  /* #119: @22 = (@22+@29) */
  w22 += w29;
  /* #120: (@20[0] = @22) */
  for (rr=w20+0, cs=(&w22); rr!=w20+1; rr+=1) *rr = *cs++;
  /* #121: @22 = @2[13] */
  w22 = wr02[13];
  /* #122: @29 = (@18*@22) */
  w29  = (w18*w22);
  /* #123: @30 = @2[12] */
  w30 = wr02[12];
  /* #124: @31 = (@23*@30) */
  w31  = (w23*w30);
  /* #125: @29 = (@29-@31) */
  w29 -= w31;
  /* #126: @31 = @2[14] */
  w31 = wr02[14];
  /* #127: @32 = (@27*@31) */
  w32  = (w27*w31);
  /* #128: @29 = (@29+@32) */
  w29 += w32;
  /* #129: @32 = @2[15] */
  w32 = wr02[15];
  /* #130: @33 = (@25*@32) */
  w33  = (w25*w32);
  /* #131: @29 = (@29-@33) */
  w29 -= w33;
  /* #132: (@20[1] = @29) */
  for (rr=w20+1, cs=(&w29); rr!=w20+2; rr+=1) *rr = *cs++;
  /* #133: @29 = @2[12] */
  w29 = wr02[12];
  /* #134: @33 = (@25*@29) */
  w33  = (w25*w29);
  /* #135: @33 = (-@33) */
  w33 = (- w33 );
  /* #136: @34 = @2[13] */
  w34 = wr02[13];
  /* #137: @35 = (@27*@34) */
  w35  = (w27*w34);
  /* #138: @33 = (@33-@35) */
  w33 -= w35;
  /* #139: @35 = @2[14] */
  w35 = wr02[14];
  /* #140: @36 = (@18*@35) */
  w36  = (w18*w35);
  /* #141: @33 = (@33+@36) */
  w33 += w36;
  /* #142: @36 = @2[15] */
  w36 = wr02[15];
  /* #143: @37 = (@23*@36) */
  w37  = (w23*w36);
  /* #144: @33 = (@33+@37) */
  w33 += w37;
  /* #145: (@20[2] = @33) */
  for (rr=w20+2, cs=(&w33); rr!=w20+3; rr+=1) *rr = *cs++;
  /* #146: @33 = @2[13] */
  w33 = wr02[13];
  /* #147: @25 = (@25*@33) */
  w25 *= w33;
  /* #148: @37 = @2[12] */
  w37 = wr02[12];
  /* #149: @27 = (@27*@37) */
  w27 *= w37;
  /* #150: @25 = (@25-@27) */
  w25 -= w27;
  /* #151: @27 = @2[14] */
  w27 = wr02[14];
  /* #152: @23 = (@23*@27) */
  w23 *= w27;
  /* #153: @25 = (@25-@23) */
  w25 -= w23;
  /* #154: @23 = @2[15] */
  w23 = wr02[15];
  /* #155: @18 = (@18*@23) */
  w18 *= w23;
  /* #156: @25 = (@25+@18) */
  w25 += w18;
  /* #157: (@20[3] = @25) */
  for (rr=w20+3, cs=(&w25); rr!=w20+4; rr+=1) *rr = *cs++;
  /* #158: @25 = @20[0] */
  for (rr=(&w25), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #159: @18 = @20[1] */
  for (rr=(&w18), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #160: @38 = (@25*@18) */
  w38  = (w25*w18);
  /* #161: @39 = @20[2] */
  for (rr=(&w39), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #162: @40 = @20[3] */
  for (rr=(&w40), cs=w20+3; cs!=w20+4; cs+=1) *rr++ = *cs;
  /* #163: @41 = (@39*@40) */
  w41  = (w39*w40);
  /* #164: @38 = (@38-@41) */
  w38 -= w41;
  /* #165: @41 = @20[0] */
  for (rr=(&w41), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #166: @42 = @20[2] */
  for (rr=(&w42), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #167: @43 = (@41*@42) */
  w43  = (w41*w42);
  /* #168: @44 = @20[1] */
  for (rr=(&w44), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #169: @45 = @20[3] */
  for (rr=(&w45), cs=w20+3; cs!=w20+4; cs+=1) *rr++ = *cs;
  /* #170: @46 = (@44*@45) */
  w46  = (w44*w45);
  /* #171: @43 = (@43+@46) */
  w43 += w46;
  /* #172: @46 = @20[3] */
  for (rr=(&w46), cs=w20+3; cs!=w20+4; cs+=1) *rr++ = *cs;
  /* #173: @47 = vertcat(@38, @43, @46) */
  rr=w47;
  *rr++ = w38;
  *rr++ = w43;
  *rr++ = w46;
  /* #174: @38 = 0.001 */
  w38 = 1.0000000000000000e-03;
  /* #175: @43 = @20[0] */
  for (rr=(&w43), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #176: @46 = sq(@43) */
  w46 = casadi_sq( w43 );
  /* #177: @48 = @20[3] */
  for (rr=(&w48), cs=w20+3; cs!=w20+4; cs+=1) *rr++ = *cs;
  /* #178: @49 = sq(@48) */
  w49 = casadi_sq( w48 );
  /* #179: @46 = (@46+@49) */
  w46 += w49;
  /* #180: @38 = (@38+@46) */
  w38 += w46;
  /* #181: @38 = sqrt(@38) */
  w38 = sqrt( w38 );
  /* #182: @47 = (@47/@38) */
  for (i=0, rr=w47; i<3; ++i) (*rr++) /= w38;
  /* #183: @50 = @47' */
  casadi_copy(w47, 3, w50);
  /* #184: @51 = 
  [[5, 0, 0], 
   [0, 5, 0], 
   [0, 0, 100]] */
  wr51 = casadi_c0;
  /* #185: @19 = mac(@50,@51,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w50+j, ct=wr51+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #186: @13 = mac(@19,@47,@13) */
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w19+j, ct=w47+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #187: @0 = (@0+@13) */
  w00 += w13;
  /* #188: @13 = 1.5 */
  w13 = 1.5000000000000000e+00;
  /* #189: @46 = input[1][0] */
  w46 = arg[1] ? arg[1][0] : 0;
  /* #190: @49 = @2[19] */
  w49 = wr02[19];
  /* #191: @46 = (@46-@49) */
  w46 -= w49;
  /* #192: @49 = sq(@46) */
  w49 = casadi_sq( w46 );
  /* #193: @13 = (@13*@49) */
  w13 *= w49;
  /* #194: @49 = 1.5 */
  w49 = 1.5000000000000000e+00;
  /* #195: @52 = input[1][1] */
  w52 = arg[1] ? arg[1][1] : 0;
  /* #196: @53 = @2[20] */
  w53 = wr02[20];
  /* #197: @52 = (@52-@53) */
  w52 -= w53;
  /* #198: @53 = sq(@52) */
  w53 = casadi_sq( w52 );
  /* #199: @49 = (@49*@53) */
  w49 *= w53;
  /* #200: @13 = (@13+@49) */
  w13 += w49;
  /* #201: @49 = 1.5 */
  w49 = 1.5000000000000000e+00;
  /* #202: @53 = input[1][2] */
  w53 = arg[1] ? arg[1][2] : 0;
  /* #203: @54 = @2[21] */
  w54 = wr02[21];
  /* #204: @53 = (@53-@54) */
  w53 -= w54;
  /* #205: @54 = sq(@53) */
  w54 = casadi_sq( w53 );
  /* #206: @49 = (@49*@54) */
  w49 *= w54;
  /* #207: @13 = (@13+@49) */
  w13 += w49;
  /* #208: @49 = 1.5 */
  w49 = 1.5000000000000000e+00;
  /* #209: @54 = input[1][3] */
  w54 = arg[1] ? arg[1][3] : 0;
  /* #210: @55 = @2[22] */
  w55 = wr02[22];
  /* #211: @54 = (@54-@55) */
  w54 -= w55;
  /* #212: @55 = sq(@54) */
  w55 = casadi_sq( w54 );
  /* #213: @49 = (@49*@55) */
  w49 *= w55;
  /* #214: @13 = (@13+@49) */
  w13 += w49;
  /* #215: @0 = (@0+@13) */
  w00 += w13;
  /* #216: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #217: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #218: @46 = (2.*@46) */
  w46 = (2.* w46 );
  /* #219: @0 = (@0*@46) */
  w00 *= w46;
  /* #220: output[1][0] = @0 */
  if (res[1]) res[1][0] = w00;
  /* #221: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #222: @52 = (2.*@52) */
  w52 = (2.* w52 );
  /* #223: @0 = (@0*@52) */
  w00 *= w52;
  /* #224: output[1][1] = @0 */
  if (res[1]) res[1][1] = w00;
  /* #225: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #226: @53 = (2.*@53) */
  w53 = (2.* w53 );
  /* #227: @0 = (@0*@53) */
  w00 *= w53;
  /* #228: output[1][2] = @0 */
  if (res[1]) res[1][2] = w00;
  /* #229: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #230: @54 = (2.*@54) */
  w54 = (2.* w54 );
  /* #231: @0 = (@0*@54) */
  w00 *= w54;
  /* #232: output[1][3] = @0 */
  if (res[1]) res[1][3] = w00;
  /* #233: @0 = 10 */
  w00 = 10.;
  /* #234: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #235: @0 = (@0*@1) */
  w00 *= w01;
  /* #236: output[1][4] = @0 */
  if (res[1]) res[1][4] = w00;
  /* #237: @0 = 10 */
  w00 = 10.;
  /* #238: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #239: @0 = (@0*@4) */
  w00 *= w04;
  /* #240: output[1][5] = @0 */
  if (res[1]) res[1][5] = w00;
  /* #241: @0 = 10 */
  w00 = 10.;
  /* #242: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #243: @0 = (@0*@5) */
  w00 *= w05;
  /* #244: output[1][6] = @0 */
  if (res[1]) res[1][6] = w00;
  /* #245: @0 = 10 */
  w00 = 10.;
  /* #246: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #247: @0 = (@0*@6) */
  w00 *= w06;
  /* #248: output[1][7] = @0 */
  if (res[1]) res[1][7] = w00;
  /* #249: @0 = 10 */
  w00 = 10.;
  /* #250: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #251: @0 = (@0*@7) */
  w00 *= w07;
  /* #252: output[1][8] = @0 */
  if (res[1]) res[1][8] = w00;
  /* #253: @0 = 10 */
  w00 = 10.;
  /* #254: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #255: @0 = (@0*@8) */
  w00 *= w08;
  /* #256: output[1][9] = @0 */
  if (res[1]) res[1][9] = w00;
  /* #257: @0 = 10 */
  w00 = 10.;
  /* #258: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #259: @0 = (@0*@9) */
  w00 *= w09;
  /* #260: output[1][10] = @0 */
  if (res[1]) res[1][10] = w00;
  /* #261: @0 = 10 */
  w00 = 10.;
  /* #262: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #263: @0 = (@0*@11) */
  w00 *= w11;
  /* #264: output[1][11] = @0 */
  if (res[1]) res[1][11] = w00;
  /* #265: @0 = 10 */
  w00 = 10.;
  /* #266: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #267: @0 = (@0*@12) */
  w00 *= w12;
  /* #268: output[1][12] = @0 */
  if (res[1]) res[1][12] = w00;
  /* #269: @0 = 10 */
  w00 = 10.;
  /* #270: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #271: @0 = (@0*@10) */
  w00 *= w10;
  /* #272: output[1][13] = @0 */
  if (res[1]) res[1][13] = w00;
  /* #273: @0 = 10 */
  w00 = 10.;
  /* #274: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #275: @0 = (@0*@14) */
  w00 *= w14;
  /* #276: output[1][14] = @0 */
  if (res[1]) res[1][14] = w00;
  /* #277: @0 = 10 */
  w00 = 10.;
  /* #278: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #279: @0 = (@0*@15) */
  w00 *= w15;
  /* #280: output[1][15] = @0 */
  if (res[1]) res[1][15] = w00;
  /* #281: @20 = zeros(4x1) */
  casadi_clear(w20, 4);
  /* #282: @48 = (2.*@48) */
  w48 = (2.* w48 );
  /* #283: @50 = (@47/@38) */
  for (i=0, rr=w50, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)/w38);
  /* #284: @50 = (-@50) */
  for (i=0, rr=w50, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #285: @19 = @19' */
  /* #286: @56 = zeros(1x3) */
  casadi_clear(w56, 3);
  /* #287: @47 = @47' */
  /* #288: @57 = @51' */
  for (i=0, rr=w57, cs=wr51; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #289: @56 = mac(@47,@57,@56) */
  for (i=0, rr=w56; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w47+j, ct=w57+i*3; k<3; ++k) *rr += cs[k*1]**ct++;
  /* #290: @56 = @56' */
  /* #291: @19 = (@19+@56) */
  for (i=0, rr=w19, cs=w56; i<3; ++i) (*rr++) += (*cs++);
  /* #292: @0 = dot(@50, @19) */
  w00 = casadi_dot(3, w50, w19);
  /* #293: @15 = (2.*@38) */
  w15 = (2.* w38 );
  /* #294: @0 = (@0/@15) */
  w00 /= w15;
  /* #295: @48 = (@48*@0) */
  w48 *= w00;
  /* #296: (@20[3] += @48) */
  for (rr=w20+3, cs=(&w48); rr!=w20+4; rr+=1) *rr += *cs++;
  /* #297: @43 = (2.*@43) */
  w43 = (2.* w43 );
  /* #298: @43 = (@43*@0) */
  w43 *= w00;
  /* #299: (@20[0] += @43) */
  for (rr=w20+0, cs=(&w43); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #300: @19 = (@19/@38) */
  for (i=0, rr=w19; i<3; ++i) (*rr++) /= w38;
  /* #301: {@38, @43, @0} = vertsplit(@19) */
  w38 = w19[0];
  w43 = w19[1];
  w00 = w19[2];
  /* #302: (@20[3] += @0) */
  for (rr=w20+3, cs=(&w00); rr!=w20+4; rr+=1) *rr += *cs++;
  /* #303: @44 = (@44*@43) */
  w44 *= w43;
  /* #304: (@20[3] += @44) */
  for (rr=w20+3, cs=(&w44); rr!=w20+4; rr+=1) *rr += *cs++;
  /* #305: @45 = (@45*@43) */
  w45 *= w43;
  /* #306: (@20[1] += @45) */
  for (rr=w20+1, cs=(&w45); rr!=w20+2; rr+=1) *rr += *cs++;
  /* #307: @41 = (@41*@43) */
  w41 *= w43;
  /* #308: (@20[2] += @41) */
  for (rr=w20+2, cs=(&w41); rr!=w20+3; rr+=1) *rr += *cs++;
  /* #309: @42 = (@42*@43) */
  w42 *= w43;
  /* #310: (@20[0] += @42) */
  for (rr=w20+0, cs=(&w42); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #311: @39 = (@39*@38) */
  w39 *= w38;
  /* #312: @39 = (-@39) */
  w39 = (- w39 );
  /* #313: (@20[3] += @39) */
  for (rr=w20+3, cs=(&w39); rr!=w20+4; rr+=1) *rr += *cs++;
  /* #314: @40 = (@40*@38) */
  w40 *= w38;
  /* #315: @40 = (-@40) */
  w40 = (- w40 );
  /* #316: (@20[2] += @40) */
  for (rr=w20+2, cs=(&w40); rr!=w20+3; rr+=1) *rr += *cs++;
  /* #317: @25 = (@25*@38) */
  w25 *= w38;
  /* #318: (@20[1] += @25) */
  for (rr=w20+1, cs=(&w25); rr!=w20+2; rr+=1) *rr += *cs++;
  /* #319: @18 = (@18*@38) */
  w18 *= w38;
  /* #320: (@20[0] += @18) */
  for (rr=w20+0, cs=(&w18); rr!=w20+1; rr+=1) *rr += *cs++;
  /* #321: @18 = @20[3] */
  for (rr=(&w18), cs=w20+3; cs!=w20+4; cs+=1) *rr++ = *cs;
  /* #322: @23 = (@23*@18) */
  w23 *= w18;
  /* #323: @38 = 0 */
  w38 = 0.;
  /* #324: (@20[3] = @38) */
  for (rr=w20+3, cs=(&w38); rr!=w20+4; rr+=1) *rr = *cs++;
  /* #325: @38 = @20[2] */
  for (rr=(&w38), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #326: @35 = (@35*@38) */
  w35 *= w38;
  /* #327: @23 = (@23+@35) */
  w23 += w35;
  /* #328: @35 = 0 */
  w35 = 0.;
  /* #329: (@20[2] = @35) */
  for (rr=w20+2, cs=(&w35); rr!=w20+3; rr+=1) *rr = *cs++;
  /* #330: @35 = @20[1] */
  for (rr=(&w35), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #331: @22 = (@22*@35) */
  w22 *= w35;
  /* #332: @23 = (@23+@22) */
  w23 += w22;
  /* #333: @22 = 0 */
  w22 = 0.;
  /* #334: (@20[1] = @22) */
  for (rr=w20+1, cs=(&w22); rr!=w20+2; rr+=1) *rr = *cs++;
  /* #335: @22 = @20[0] */
  for (rr=(&w22), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #336: @21 = (@21*@22) */
  w21 *= w22;
  /* #337: @23 = (@23+@21) */
  w23 += w21;
  /* #338: output[1][16] = @23 */
  if (res[1]) res[1][16] = w23;
  /* #339: @36 = (@36*@38) */
  w36 *= w38;
  /* #340: @27 = (@27*@18) */
  w27 *= w18;
  /* #341: @36 = (@36-@27) */
  w36 -= w27;
  /* #342: @30 = (@30*@35) */
  w30 *= w35;
  /* #343: @36 = (@36-@30) */
  w36 -= w30;
  /* #344: @24 = (@24*@22) */
  w24 *= w22;
  /* #345: @36 = (@36+@24) */
  w36 += w24;
  /* #346: output[1][17] = @36 */
  if (res[1]) res[1][17] = w36;
  /* #347: @33 = (@33*@18) */
  w33 *= w18;
  /* #348: @29 = (@29*@38) */
  w29 *= w38;
  /* #349: @33 = (@33-@29) */
  w33 -= w29;
  /* #350: @32 = (@32*@35) */
  w32 *= w35;
  /* #351: @33 = (@33-@32) */
  w33 -= w32;
  /* #352: @26 = (@26*@22) */
  w26 *= w22;
  /* #353: @33 = (@33+@26) */
  w33 += w26;
  /* #354: output[1][18] = @33 */
  if (res[1]) res[1][18] = w33;
  /* #355: @34 = (@34*@38) */
  w34 *= w38;
  /* #356: @34 = (-@34) */
  w34 = (- w34 );
  /* #357: @37 = (@37*@18) */
  w37 *= w18;
  /* #358: @34 = (@34-@37) */
  w34 -= w37;
  /* #359: @31 = (@31*@35) */
  w31 *= w35;
  /* #360: @34 = (@34+@31) */
  w34 += w31;
  /* #361: @28 = (@28*@22) */
  w28 *= w22;
  /* #362: @34 = (@34+@28) */
  w34 += w28;
  /* #363: output[1][19] = @34 */
  if (res[1]) res[1][19] = w34;
  /* #364: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #365: @3 = (2.*@3) */
  w03 = (2.* w03 );
  /* #366: output[1][20] = @3 */
  if (res[1]) res[1][20] = w03;
  /* #367: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #368: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #369: output[1][21] = @16 */
  if (res[1]) res[1][21] = w16;
  /* #370: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #371: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #372: output[1][22] = @17 */
  if (res[1]) res[1][22] = w17;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 108;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 108*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
